
#include "1_TaskerManager/mTaskerManager.h"

#include "2_CoreSystem/11_Languages/mLanguageDefault.h" // patch 3apr26


#pragma once



// Friendly names of gpio functions (add ifdefs later)

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NONE_CTR)              D_GPIO_FUNCTION_NONE_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_UNUSED_FORCED_LOW_CTR)         D_GPIO_FUNCTION_UNUSED_FORCED_LOW_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_UNUSED_FORCED_HIGH_CTR)        D_GPIO_FUNCTION_UNUSED_FORCED_HIGH_CTR;

  #ifdef USE_MODULE_CORE_PWM
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM1_CTR)          D_GPIO_FUNCTION_PWM1_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM2_CTR)          D_GPIO_FUNCTION_PWM2_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM3_CTR)          D_GPIO_FUNCTION_PWM3_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM4_CTR)          D_GPIO_FUNCTION_PWM4_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM5_CTR)          D_GPIO_FUNCTION_PWM5_CTR;

  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM1_INV_CTR)          D_GPIO_FUNCTION_PWM1_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM2_INV_CTR)          D_GPIO_FUNCTION_PWM2_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM3_INV_CTR)          D_GPIO_FUNCTION_PWM3_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM4_INV_CTR)          D_GPIO_FUNCTION_PWM4_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM5_INV_CTR)          D_GPIO_FUNCTION_PWM5_INV_CTR;
  #endif




// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ANALOG_CTR)      D_GPIO_FUNCTION_ANALOG_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT11_1_CTR)           D_GPIO_FUNCTION_DHT11_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT11_2_CTR)           D_GPIO_FUNCTION_DHT11_2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT22_1_CTR)           D_GPIO_FUNCTION_DHT22_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT22_2_CTR)           D_GPIO_FUNCTION_DHT22_2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_AM2301_1_CTR)          D_GPIO_FUNCTION_AM2301_CTR "_1";
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_AM2301_2_CTR)          D_GPIO_FUNCTION_AM2301_CTR "_2";

#ifdef USE_MODULE_CORE_I2C
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SCL_CTR)           D_GPIO_FUNCTION_I2C_SCL_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SDA_CTR)           D_GPIO_FUNCTION_I2C_SDA_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SCL2_CTR)           D_GPIO_FUNCTION_I2C_SCL2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SDA2_CTR)           D_GPIO_FUNCTION_I2C_SDA2_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_DIGITAL1_CTR)     D_GPIO_FUNCTION_LDR_BASIC_DIGITAL1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_ANALOG1_CTR)      D_GPIO_FUNCTION_LDR_BASIC_ANALOG1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_DIGITAL2_CTR)     D_GPIO_FUNCTION_LDR_BASIC_DIGITAL2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_ANALOG2_CTR)      D_GPIO_FUNCTION_LDR_BASIC_ANALOG2_CTR;

#if defined(USE_MODULE_DISPLAYS_OLED_SH1106) || defined(USE_MODULE_DISPLAYS_OLED_SSD1306)
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_OLED_RESET_CTR)           D_GPIO_FUNCTION_OLED_RESET_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_DATA_CTR)          D_GPIO_FUNCTION_RGB_DATA_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_DATA1_CTR)          D_GPIO_FUNCTION_RGB_DATA1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_CLOCK_CTR)         D_GPIO_FUNCTION_RGB_CLOCK_CTR;

#ifdef USE_MODULE_SENSORS_PIR
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_1_CTR)             D_GPIO_FUNCTION_PIR_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_2_CTR)             D_GPIO_FUNCTION_PIR_2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_3_CTR)             D_GPIO_FUNCTION_PIR_3_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_4_CTR)             D_GPIO_FUNCTION_PIR_4_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_1_INV_CTR)         D_GPIO_FUNCTION_PIR_1_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_2_INV_CTR)         D_GPIO_FUNCTION_PIR_2_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_3_INV_CTR)         D_GPIO_FUNCTION_PIR_3_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_4_INV_CTR)         D_GPIO_FUNCTION_PIR_4_INV_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_BUZZER_CTR) D_GPIO_FUNCTION_BUZZER_CTR;

#ifdef USE_MODULE_CONTROLLER_DOORCHIME
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CHIME_INPUT_CTR)       D_GPIO_FUNCTION_CHIME_INPUT_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CHIME_RINGER_CTR)      D_GPIO_FUNCTION_CHIME_RINGER_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_IRSEND_CTR)            D_GPIO_FUNCTION_IRSEND_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_FAN_IRSEND_CTR)        D_GPIO_FUNCTION_FAN_IRSEND_CTR;

#ifdef USE_MODULE_DRIVERS_RELAY
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL1_CTR)          D_GPIO_FUNCTION_REL1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL2_CTR)          D_GPIO_FUNCTION_REL2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL3_CTR)          D_GPIO_FUNCTION_REL3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL4_CTR)          D_GPIO_FUNCTION_REL4_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL1_INV_CTR)          D_GPIO_FUNCTION_REL1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL2_INV_CTR)          D_GPIO_FUNCTION_REL2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL3_INV_CTR)          D_GPIO_FUNCTION_REL3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL4_INV_CTR)          D_GPIO_FUNCTION_REL4_INV_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL_NUM_CTR)           "Relay %d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL_NUM_INV_CTR)         "Relay %d Inv";

#endif 

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_MOISTURE_ANALOG_CTR)   D_GPIO_FUNCTION_MOISTURE_ANALOG_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_FAN_PWM1_CTR)          D_GPIO_FUNCTION_FAN_PWM1_CTR;


#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_TX_CTR) D_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_RX_CTR) D_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_TX_CTR) D_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_RX_CTR) D_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_RX_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL0_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL0_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL0_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL0_RX_CTR;
#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL1_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL1_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL2_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL2_RX_CTR;
#endif


DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR)   D_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR)   D_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN1_CTR) D_GPIO_FUNCTION_DEBUG_PIN1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN2_CTR) D_GPIO_FUNCTION_DEBUG_PIN2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN3_CTR) D_GPIO_FUNCTION_DEBUG_PIN3_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL0_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL0_TX_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL0_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL0_RX_CTR;

#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL1_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL1_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL1_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL1_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL2_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL2_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL2_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL2_RX_CTR;
#endif // ESP32

#ifdef USE_MODULE_DRIVERS_LEDS
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LED_NUM_CTR)           "Led%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LED_NUM_INV_CTR)         "Led%d Inv";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_STATUS_LED_CTR)           D_GPIO_FUNCTION_STATUS_LED_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_STATUS_LED_INV_CTR)         D_GPIO_FUNCTION_STATUS_LED_INV_CTR;
#endif

#ifdef USE_MODULE_ENERGY_PZEM004T_V3
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM0XX_TX_CTR)     D_GPIO_FUNCTION_PZEM0XX_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM0XX_MODBUS__RX_CTR)     D_GPIO_FUNCTION_PZEM0XX_RX_MODBUS_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM004_RX_CTR)     D_GPIO_FUNCTION_PZEM004_RX_CTR;
#endif

#ifdef USE_MODULE_SENSORS_SR04
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SR04_ECHO_CTR)     D_GPIO_FUNCTION_SR04_ECHO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SR04_TRIG_CTR)     D_GPIO_FUNCTION_SR04_TRIG_CTR;
#endif

#ifdef USE_MODULE_SENSORS__RADAR_HLK_LD2410
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__HLK_LD2410_RX__CTR)     D_GPIO_FUNCTION__HLK_LD2410_RX__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__HLK_LD2410_TX__CTR)     D_GPIO_FUNCTION__HLK_LD2410_TX__CTR;
#endif

// // #ifdef USE_MODULE_SENSORS_
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__ROTARY_ENCODER_A__CTR)     D_GPIO_FUNCTION__ROTARY_ENCODER_A__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__ROTARY_ENCODER_B__CTR)     D_GPIO_FUNCTION__ROTARY_ENCODER_B__CTR;
// // #endif


/******************************************************************************************************************
 * Network
*******************************************************************************************************************/

/******************************************************************************************************************
 * Drivers
*******************************************************************************************************************/

#ifdef USE_MODULE_DRIVERS_SHELLY_DIMMER
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SHELLY2_SHD_BOOT0_CTR)           D_GPIO_FUNCTION_SHELLY2_SHD_BOOT0_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SHELLY2_SHD_RESET_INV_CTR)       D_GPIO_FUNCTION_SHELLY2_SHD_RESET_INV_CTR;
#endif


/******************************************************************************************************************
 * Sensors
*******************************************************************************************************************/

#ifdef USE_MODULE_SENSORS_SWITCHES
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_CTR)         D_GPIO_FUNCTION_SWT1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_CTR)         D_GPIO_FUNCTION_SWT2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT3_CTR)         D_GPIO_FUNCTION_SWT3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT4_CTR)         D_GPIO_FUNCTION_SWT3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT5_CTR)         D_GPIO_FUNCTION_SWT4_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT6_CTR)         D_GPIO_FUNCTION_SWT5_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT7_CTR)         D_GPIO_FUNCTION_SWT6_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT8_CTR)         D_GPIO_FUNCTION_SWT7_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_INV_CTR)         D_GPIO_FUNCTION_SWT1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_INV_CTR)         D_GPIO_FUNCTION_SWT2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT3_INV_CTR)         D_GPIO_FUNCTION_SWT3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT4_INV_CTR)         D_GPIO_FUNCTION_SWT4_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT5_INV_CTR)         D_GPIO_FUNCTION_SWT5_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT6_INV_CTR)         D_GPIO_FUNCTION_SWT6_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT7_INV_CTR)         D_GPIO_FUNCTION_SWT7_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT8_INV_CTR)         D_GPIO_FUNCTION_SWT8_INV_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_NP_CTR)         D_GPIO_FUNCTION_SWT1_NP_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_NP_CTR)         D_GPIO_FUNCTION_SWT2_NP_CTR;



DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_CTR)           "SWT%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_INV_CTR)         "SWT%dInv";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_NP_CTR)         "SWT%dNP";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_INV_NP_CTR)         "SWT%dInvNP";

#endif // USE_MODULE_SENSORS_SWITCHES

#ifdef USE_MODULE_SENSORS_BUTTONS
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_CTR)      D_GPIO_FUNCTION_KEY1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_CTR)      D_GPIO_FUNCTION_KEY2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_CTR)      D_GPIO_FUNCTION_KEY3_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_INV_CTR)      D_GPIO_FUNCTION_KEY1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_INV_CTR)      D_GPIO_FUNCTION_KEY2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_INV_CTR)      D_GPIO_FUNCTION_KEY3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY4_INV_CTR)      D_GPIO_FUNCTION_KEY4_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY5_INV_CTR)      D_GPIO_FUNCTION_KEY5_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY6_INV_CTR)      D_GPIO_FUNCTION_KEY6_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY7_INV_CTR)      D_GPIO_FUNCTION_KEY7_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY8_INV_CTR)      D_GPIO_FUNCTION_KEY8_INV_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_TOUCH_CTR)      D_GPIO_FUNCTION_KEY1_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_TOUCH_CTR)      D_GPIO_FUNCTION_KEY2_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_TOUCH_CTR)      D_GPIO_FUNCTION_KEY3_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY4_TOUCH_CTR)      D_GPIO_FUNCTION_KEY4_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY5_TOUCH_CTR)      D_GPIO_FUNCTION_KEY5_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY6_TOUCH_CTR)      D_GPIO_FUNCTION_KEY6_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY7_TOUCH_CTR)      D_GPIO_FUNCTION_KEY7_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY8_TOUCH_CTR)      D_GPIO_FUNCTION_KEY8_TOUCH_CTR;


// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_NP_CTR)      D_GPIO_FUNCTION_KEY1_NP_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_PULLDOWN_CTR)      D_GPIO_FUNCTION_KEY1_PULLDOWN_CTR;


DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_CTR)           "Key%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_INV_CTR)       "Key%d Inv";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_NP_CTR)        "Key%d NP";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_INV_NP_CTR)    "Key%d PD";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_TOUCH_CTR)     "Key%d Touch";



#endif // USE_MODULE_SENSORS_BUTTONS

#ifdef USE_MODULE_SENSORS_DS18X20
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DS18X20_1_CTR)         D_GPIO_FUNCTION_DS18X20_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DS18X20_2_CTR)         D_GPIO_FUNCTION_DS18X20_2_CTR;
#endif

#ifdef USE_MODULE_SENSORS_DOOR
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DOOR_OPEN_CTR)           D_GPIO_FUNCTION_DOOR_OPEN_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DOOR_LOCK_CTR)           D_GPIO_FUNCTION_DOOR_LOCK_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION__TOF_VL53L0X_XSHUTNUM__CTR)           D_GPIO_FUNCTION__TOF_VL53L0X_XSHUTNUM__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__TOF_VL53L1X_XSHUTNUM__CTR)         D_GPIO_FUNCTION__TOF_VL53L1X_XSHUTNUM__CTR;



/******************************************************************************************************************
 * Lights
*******************************************************************************************************************/

/******************************************************************************************************************
 * Energy
*******************************************************************************************************************/

#ifdef USE_MODULE_ENERGY_ADE7953
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADE7953_IRQ_CTR)  D_GPIO_FUNCTION_ADE7953_IRQ_CTR;
#endif

/******************************************************************************************************************
 * Displays
*******************************************************************************************************************/
#ifdef USE_MODULE_DISPLAYS_NEXTION
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NEXTION_TX_CTR)     D_GPIO_FUNCTION_NEXTION_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NEXTION_RX_CTR)     D_GPIO_FUNCTION_NEXTION_RX_CTR;
#endif // USE_MODULE_DISPLAYS_NEXTION

DEFINE_PGM_CTR(PM_GPIO_FUNCTION__RF_433MHZ_RX__CTR)      D_GPIO_FUNCTION__RF_433MHZ_RX__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__RF_433MHZ_TX__CTR)      D_GPIO_FUNCTION__RF_433MHZ_TX__CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR)  D_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR)  D_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_POWER_KEY__CTR)       D_GPIO_FUNCTION__FONA_POWER_KEY__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_POWER_STATUS__CTR)    D_GPIO_FUNCTION__FONA_POWER_STATUS__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_NETWORK_STATUS__CTR)  D_GPIO_FUNCTION__FONA_NETWORK_STATUS__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_RESET__CTR)           D_GPIO_FUNCTION__FONA_RESET__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_UART_TX__CTR)         D_GPIO_FUNCTION__FONA_UART_TX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_UART_RX__CTR)         D_GPIO_FUNCTION__FONA_UART_RX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_RING_INDICATOR__CTR)  D_GPIO_FUNCTION__FONA_RING_INDICATOR__CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_DATA_TERMINAL_READY_DTR__CTR)           D_GPIO_FUNCTION__MODEM_DATA_TERMINAL_READY_DTR__CTR;



DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_RX0__CTR)  D_GPIO_FUNCTION__MODEM_RX0__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_TX0__CTR)  D_GPIO_FUNCTION__MODEM_TX0__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_RX1__CTR)  D_GPIO_FUNCTION__MODEM_RX1__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_TX1__CTR)  D_GPIO_FUNCTION__MODEM_TX1__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_RX2__CTR)  D_GPIO_FUNCTION__MODEM_RX2__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_TX2__CTR)  D_GPIO_FUNCTION__MODEM_TX2__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_POWER_KEY__CTR)  D_GPIO_FUNCTION__MODEM_POWER_KEY__CTR;



#ifdef USE_MODULE_DRIVERS_HBRIDGE
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_IA_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_IA_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_IB_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_IB_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_OA_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_OA_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_OB_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_OB_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ANALOG_POSITION_CTR) D_GPIO_FUNCTION_ANALOG_POSITION_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH4_CTR) D_GPIO_FUNCTION_ADC1_CH4_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH6_CTR) D_GPIO_FUNCTION_ADC1_CH6_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH7_CTR) D_GPIO_FUNCTION_ADC1_CH7_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_EXTERNAL_INTERRUPT_TRIGGER_CTR) D_GPIO_FUNCTION_EXTERNAL_INTERRUPT_TRIGGER_CTR;


#ifdef ESP32


// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RXON_SAMPLING_ENABLED_CTR)   D_GPIO_FUNCTION_RXON_SAMPLING_ENABLED_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CC1110_SYNC_PULSE_SIGNAL_CTR)   D_GPIO_FUNCTION_CC1110_SYNC_PULSE_SIGNAL_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_XCLK_CTR)            D_GPIO_WEBCAM_XCLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_DATA_NUM_CTR)         "Cam Data%d"; // 1-8
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_PCLK_CTR)            D_GPIO_WEBCAM_PCLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_HREF_CTR)            D_GPIO_WEBCAM_HREF_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_VSYNC_CTR)            D_GPIO_WEBCAM_VSYNC_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_SIOD_CTR)            D_GPIO_WEBCAM_SIOD_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_SIOC_CTR)            D_GPIO_WEBCAM_SIOC_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_PWDN_CTR)            D_GPIO_WEBCAM_PWDN_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_CSO_CTR)   D_GPIO_FUNCTION_SDCARD_VSPI_CSO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_CLK_CTR)   D_GPIO_FUNCTION_SDCARD_VSPI_CLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_MOSI_CTR)  D_GPIO_FUNCTION_SDCARD_VSPI_MOSI_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_MISO_CTR)  D_GPIO_FUNCTION_SDCARD_VSPI_MISO_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_CSO_CTR)   D_GPIO_FUNCTION_SDCARD_HSPI_CSO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_CLK_CTR)   D_GPIO_FUNCTION_SDCARD_HSPI_CLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_MOSI_CTR)  D_GPIO_FUNCTION_SDCARD_HSPI_MOSI_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_MISO_CTR)  D_GPIO_FUNCTION_SDCARD_HSPI_MISO_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_CLK_CTR)   D_GPIO_FUNCTION_SDCARD_MMC_CLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_CMD_CTR)   D_GPIO_FUNCTION_SDCARD_MMC_CMD_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_D0_CTR)  D_GPIO_FUNCTION_SDCARD_MMC_D0_CTR;  
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_D1_CTR)  D_GPIO_FUNCTION_SDCARD_MMC_D1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_D2_CTR)  D_GPIO_FUNCTION_SDCARD_MMC_D2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_MMC_D3_CTR)  D_GPIO_FUNCTION_SDCARD_MMC_D3_CTR;

#endif