#ifndef _mPin_GPIO_H_
#define _mPin_GPIO_H_

#include "1_TaskerManager/mTaskerManager.h"

// Friendly names of gpio functions (add ifdefs later)

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NONE_CTR)              D_GPIO_FUNCTION_NONE_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_UNUSED_FORCED_LOW_CTR)         D_GPIO_FUNCTION_UNUSED_FORCED_LOW_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_UNUSED_FORCED_HIGH_CTR)        D_GPIO_FUNCTION_UNUSED_FORCED_HIGH_CTR;

  #ifdef USE_MODULE_CORE_PWM
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM1_CTR)          D_GPIO_FUNCTION_PWM1_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM2_CTR)          D_GPIO_FUNCTION_PWM2_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM3_CTR)          D_GPIO_FUNCTION_PWM3_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM4_CTR)          D_GPIO_FUNCTION_PWM4_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM5_CTR)          D_GPIO_FUNCTION_PWM5_CTR;

  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM1_INV_CTR)          D_GPIO_FUNCTION_PWM1_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM2_INV_CTR)          D_GPIO_FUNCTION_PWM2_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM3_INV_CTR)          D_GPIO_FUNCTION_PWM3_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM4_INV_CTR)          D_GPIO_FUNCTION_PWM4_INV_CTR;
  DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PWM5_INV_CTR)          D_GPIO_FUNCTION_PWM5_INV_CTR;
  #endif




// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ANALOG_CTR)      D_GPIO_FUNCTION_ANALOG_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT11_1_CTR)           D_GPIO_FUNCTION_DHT11_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT11_2_CTR)           D_GPIO_FUNCTION_DHT11_2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT22_1_CTR)           D_GPIO_FUNCTION_DHT22_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DHT22_2_CTR)           D_GPIO_FUNCTION_DHT22_2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_AM2301_1_CTR)          D_GPIO_FUNCTION_AM2301_CTR "_1";
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_AM2301_2_CTR)          D_GPIO_FUNCTION_AM2301_CTR "_2";

#ifdef USE_MODULE_CORE_I2C
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SCL_CTR)           D_GPIO_FUNCTION_I2C_SCL_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_I2C_SDA_CTR)           D_GPIO_FUNCTION_I2C_SDA_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_DIGITAL1_CTR)     D_GPIO_FUNCTION_LDR_BASIC_DIGITAL1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_ANALOG1_CTR)      D_GPIO_FUNCTION_LDR_BASIC_ANALOG1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_DIGITAL2_CTR)     D_GPIO_FUNCTION_LDR_BASIC_DIGITAL2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LDR_BASIC_ANALOG2_CTR)      D_GPIO_FUNCTION_LDR_BASIC_ANALOG2_CTR;

#if defined(USE_MODULE_DISPLAYS_OLED_SH1106) || defined(USE_MODULE_DISPLAYS_OLED_SSD1306)
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_OLED_RESET_CTR)           D_GPIO_FUNCTION_OLED_RESET_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_DATA_CTR)          D_GPIO_FUNCTION_RGB_DATA_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_DATA1_CTR)          D_GPIO_FUNCTION_RGB_DATA1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RGB_CLOCK_CTR)         D_GPIO_FUNCTION_RGB_CLOCK_CTR;

#ifdef USE_MODULE_SENSORS_PIR
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_1_CTR)             D_GPIO_FUNCTION_PIR_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_2_CTR)             D_GPIO_FUNCTION_PIR_2_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_3_CTR)             D_GPIO_FUNCTION_PIR_3_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_4_CTR)             D_GPIO_FUNCTION_PIR_4_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_1_INV_CTR)         D_GPIO_FUNCTION_PIR_1_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_2_INV_CTR)         D_GPIO_FUNCTION_PIR_2_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_3_INV_CTR)         D_GPIO_FUNCTION_PIR_3_INV_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PIR_4_INV_CTR)         D_GPIO_FUNCTION_PIR_4_INV_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_BUZZER_CTR) D_GPIO_FUNCTION_BUZZER_CTR;

#ifdef USE_MODULE_CONTROLLER_DOORCHIME
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CHIME_INPUT_CTR)       D_GPIO_FUNCTION_CHIME_INPUT_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CHIME_RINGER_CTR)      D_GPIO_FUNCTION_CHIME_RINGER_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_IRSEND_CTR)            D_GPIO_FUNCTION_IRSEND_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_FAN_IRSEND_CTR)        D_GPIO_FUNCTION_FAN_IRSEND_CTR;

#ifdef USE_MODULE_DRIVERS_RELAY
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL1_CTR)          D_GPIO_FUNCTION_REL1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL2_CTR)          D_GPIO_FUNCTION_REL2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL3_CTR)          D_GPIO_FUNCTION_REL3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL4_CTR)          D_GPIO_FUNCTION_REL4_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL1_INV_CTR)          D_GPIO_FUNCTION_REL1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL2_INV_CTR)          D_GPIO_FUNCTION_REL2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL3_INV_CTR)          D_GPIO_FUNCTION_REL3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL4_INV_CTR)          D_GPIO_FUNCTION_REL4_INV_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL_NUM_CTR)           "Relay %d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_REL_NUM_INV_CTR)         "Relay %d Inv";

#endif 

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_MOISTURE_ANALOG_CTR)   D_GPIO_FUNCTION_MOISTURE_ANALOG_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_FAN_PWM1_CTR)          D_GPIO_FUNCTION_FAN_PWM1_CTR;


#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_TX_CTR) D_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_RX_CTR) D_GPIO_FUNCTION_HWSERIAL1_RING_BUFFER_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_TX_CTR) D_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_RX_CTR) D_GPIO_FUNCTION_HWSERIAL2_RING_BUFFER_RX_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL0_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL0_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL0_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL0_RX_CTR;
#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL1_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL1_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL1_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_TX_CTR)   D_GPIO_FUNCTION_HWSERIAL2_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HWSERIAL2_RX_CTR)   D_GPIO_FUNCTION_HWSERIAL2_RX_CTR;
#endif

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN1_CTR) D_GPIO_FUNCTION_DEBUG_PIN1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN2_CTR) D_GPIO_FUNCTION_DEBUG_PIN2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DEBUG_PIN3_CTR) D_GPIO_FUNCTION_DEBUG_PIN3_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL0_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL0_TX_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL0_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL0_RX_CTR;

#ifdef ESP32
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL1_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL1_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL1_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL1_RX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL2_TX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL2_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_GPS_SERIAL2_RX_CTR)   D_GPIO_FUNCTION_GPS_SERIAL2_RX_CTR;
#endif // ESP32

#ifdef USE_MODULE_DRIVERS_LEDS
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LED_NUM_CTR)           "Led%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_LED_NUM_INV_CTR)         "Led%d Inv";
#endif

#ifdef USE_MODULE_ENERGY_PZEM004T_V3
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM0XX_TX_CTR)     D_GPIO_FUNCTION_PZEM0XX_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM0XX_MODBUS__RX_CTR)     D_GPIO_FUNCTION_PZEM0XX_RX_MODBUS_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_PZEM004_RX_CTR)     D_GPIO_FUNCTION_PZEM004_RX_CTR;
#endif

#ifdef USE_MODULE_SENSORS_SR04
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SR04_ECHO_CTR)     D_GPIO_FUNCTION_SR04_ECHO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SR04_TRIG_CTR)     D_GPIO_FUNCTION_SR04_TRIG_CTR;
#endif

#ifdef USE_MODULE_SENSORS__RADAR_HLK_LD2410
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__HLK_LD2410_RX__CTR)     D_GPIO_FUNCTION__HLK_LD2410_RX__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__HLK_LD2410_TX__CTR)     D_GPIO_FUNCTION__HLK_LD2410_TX__CTR;
#endif

// // #ifdef USE_MODULE_SENSORS_
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__ROTARY_ENCODER_A__CTR)     D_GPIO_FUNCTION__ROTARY_ENCODER_A__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__ROTARY_ENCODER_B__CTR)     D_GPIO_FUNCTION__ROTARY_ENCODER_B__CTR;
// // #endif


/******************************************************************************************************************
 * Network
*******************************************************************************************************************/

/******************************************************************************************************************
 * Drivers
*******************************************************************************************************************/

#ifdef USE_MODULE_DRIVERS_SHELLY_DIMMER
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SHELLY2_SHD_BOOT0_CTR)           D_GPIO_FUNCTION_SHELLY2_SHD_BOOT0_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SHELLY2_SHD_RESET_INV_CTR)       D_GPIO_FUNCTION_SHELLY2_SHD_RESET_INV_CTR;
#endif


/******************************************************************************************************************
 * Sensors
*******************************************************************************************************************/

#ifdef USE_MODULE_SENSORS_SWITCHES
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_CTR)         D_GPIO_FUNCTION_SWT1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_CTR)         D_GPIO_FUNCTION_SWT2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT3_CTR)         D_GPIO_FUNCTION_SWT3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT4_CTR)         D_GPIO_FUNCTION_SWT3_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT5_CTR)         D_GPIO_FUNCTION_SWT4_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT6_CTR)         D_GPIO_FUNCTION_SWT5_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT7_CTR)         D_GPIO_FUNCTION_SWT6_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT8_CTR)         D_GPIO_FUNCTION_SWT7_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_INV_CTR)         D_GPIO_FUNCTION_SWT1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_INV_CTR)         D_GPIO_FUNCTION_SWT2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT3_INV_CTR)         D_GPIO_FUNCTION_SWT3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT4_INV_CTR)         D_GPIO_FUNCTION_SWT4_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT5_INV_CTR)         D_GPIO_FUNCTION_SWT5_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT6_INV_CTR)         D_GPIO_FUNCTION_SWT6_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT7_INV_CTR)         D_GPIO_FUNCTION_SWT7_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT8_INV_CTR)         D_GPIO_FUNCTION_SWT8_INV_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT1_NP_CTR)         D_GPIO_FUNCTION_SWT1_NP_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT2_NP_CTR)         D_GPIO_FUNCTION_SWT2_NP_CTR;



DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_CTR)           "SWT%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_INV_CTR)         "SWT%dInv";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_NP_CTR)         "SWT%dNP";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SWT_NUM_INV_NP_CTR)         "SWT%dInvNP";

#endif // USE_MODULE_SENSORS_SWITCHES

#ifdef USE_MODULE_SENSORS_BUTTONS
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_CTR)      D_GPIO_FUNCTION_KEY1_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_CTR)      D_GPIO_FUNCTION_KEY2_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_CTR)      D_GPIO_FUNCTION_KEY3_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_INV_CTR)      D_GPIO_FUNCTION_KEY1_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_INV_CTR)      D_GPIO_FUNCTION_KEY2_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_INV_CTR)      D_GPIO_FUNCTION_KEY3_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY4_INV_CTR)      D_GPIO_FUNCTION_KEY4_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY5_INV_CTR)      D_GPIO_FUNCTION_KEY5_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY6_INV_CTR)      D_GPIO_FUNCTION_KEY6_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY7_INV_CTR)      D_GPIO_FUNCTION_KEY7_INV_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY8_INV_CTR)      D_GPIO_FUNCTION_KEY8_INV_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_TOUCH_CTR)      D_GPIO_FUNCTION_KEY1_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY2_TOUCH_CTR)      D_GPIO_FUNCTION_KEY2_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY3_TOUCH_CTR)      D_GPIO_FUNCTION_KEY3_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY4_TOUCH_CTR)      D_GPIO_FUNCTION_KEY4_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY5_TOUCH_CTR)      D_GPIO_FUNCTION_KEY5_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY6_TOUCH_CTR)      D_GPIO_FUNCTION_KEY6_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY7_TOUCH_CTR)      D_GPIO_FUNCTION_KEY7_TOUCH_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY8_TOUCH_CTR)      D_GPIO_FUNCTION_KEY8_TOUCH_CTR;


// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_NP_CTR)      D_GPIO_FUNCTION_KEY1_NP_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY1_PULLDOWN_CTR)      D_GPIO_FUNCTION_KEY1_PULLDOWN_CTR;


DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_CTR)           "Key%d";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_INV_CTR)       "Key%d Inv";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_NP_CTR)        "Key%d NP";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_INV_NP_CTR)    "Key%d PD";
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_KEY_NUM_TOUCH_CTR)     "Key%d Touch";



#endif // USE_MODULE_SENSORS_BUTTONS

#ifdef USE_MODULE_SENSORS_DS18X20
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DS18X20_1_CTR)         D_GPIO_FUNCTION_DS18X20_1_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DS18X20_2_CTR)         D_GPIO_FUNCTION_DS18X20_2_CTR;
#endif

#ifdef USE_MODULE_SENSORS_DOOR
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DOOR_OPEN_CTR)           D_GPIO_FUNCTION_DOOR_OPEN_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_DOOR_LOCK_CTR)           D_GPIO_FUNCTION_DOOR_LOCK_CTR;
#endif

DEFINE_PGM_CTR(PM_GPIO_FUNCTION__TOF_VL53L0X_XSHUTNUM__CTR)           D_GPIO_FUNCTION__TOF_VL53L0X_XSHUTNUM__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__TOF_VL53L1X_XSHUTNUM__CTR)         D_GPIO_FUNCTION__TOF_VL53L1X_XSHUTNUM__CTR;



/******************************************************************************************************************
 * Lights
*******************************************************************************************************************/

/******************************************************************************************************************
 * Energy
*******************************************************************************************************************/

#ifdef USE_MODULE_ENERGY_ADE7953
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADE7953_IRQ_CTR)  D_GPIO_FUNCTION_ADE7953_IRQ_CTR;
#endif

/******************************************************************************************************************
 * Displays
*******************************************************************************************************************/
#ifdef USE_MODULE_DISPLAYS_NEXTION
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NEXTION_TX_CTR)     D_GPIO_FUNCTION_NEXTION_TX_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_NEXTION_RX_CTR)     D_GPIO_FUNCTION_NEXTION_RX_CTR;
#endif // USE_MODULE_DISPLAYS_NEXTION

DEFINE_PGM_CTR(PM_GPIO_FUNCTION__RF_433MHZ_RX__CTR)      D_GPIO_FUNCTION__RF_433MHZ_RX__CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION__RF_433MHZ_TX__CTR)      D_GPIO_FUNCTION__RF_433MHZ_TX__CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR)  D_GPIO_FUNCTION_SERIAL_DEBUG_TX_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR)  D_GPIO_FUNCTION_SERIAL_DEBUG_RX_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_POWER_KEY__CTR)       D_GPIO_FUNCTION__FONA_POWER_KEY__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_POWER_STATUS__CTR)    D_GPIO_FUNCTION__FONA_POWER_STATUS__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_NETWORK_STATUS__CTR)  D_GPIO_FUNCTION__FONA_NETWORK_STATUS__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_RESET__CTR)           D_GPIO_FUNCTION__FONA_RESET__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_UART_TX__CTR)         D_GPIO_FUNCTION__FONA_UART_TX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_UART_RX__CTR)         D_GPIO_FUNCTION__FONA_UART_RX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__FONA_RING_INDICATOR__CTR)  D_GPIO_FUNCTION__FONA_RING_INDICATOR__CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_DATA_TERMINAL_READY_DTR__CTR)           D_GPIO_FUNCTION__MODEM_DATA_TERMINAL_READY_DTR__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_TX__CTR)         D_GPIO_FUNCTION__MODEM_TX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_RX__CTR)         D_GPIO_FUNCTION__MODEM_RX__CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION__MODEM_POWER__CTR)  D_GPIO_FUNCTION__MODEM_POWER__CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_IA_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_IA_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_IB_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_IB_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_OA_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_OA_CTR;
// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_HBRIDGE_L9110_OB_CTR) D_GPIO_FUNCTION_HBRIDGE_L9110_OB_CTR;

// DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ANALOG_POSITION_CTR) D_GPIO_FUNCTION_ANALOG_POSITION_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH4_CTR) D_GPIO_FUNCTION_ADC1_CH4_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH6_CTR) D_GPIO_FUNCTION_ADC1_CH6_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_ADC1_CH7_CTR) D_GPIO_FUNCTION_ADC1_CH7_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_EXTERNAL_INTERRUPT_TRIGGER_CTR) D_GPIO_FUNCTION_EXTERNAL_INTERRUPT_TRIGGER_CTR;


#ifdef ESP32


DEFINE_PGM_CTR(PM_GPIO_FUNCTION_RXON_SAMPLING_ENABLED_CTR)   D_GPIO_FUNCTION_RXON_SAMPLING_ENABLED_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_CC1110_SYNC_PULSE_SIGNAL_CTR)   D_GPIO_FUNCTION_CC1110_SYNC_PULSE_SIGNAL_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_XCLK_CTR)            D_GPIO_WEBCAM_XCLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_DATA_NUM_CTR)         "Cam Data%d"; // 1-8
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_PCLK_CTR)            D_GPIO_WEBCAM_PCLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_HREF_CTR)            D_GPIO_WEBCAM_HREF_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_VSYNC_CTR)            D_GPIO_WEBCAM_VSYNC_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_SIOD_CTR)            D_GPIO_WEBCAM_SIOD_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_SIOC_CTR)            D_GPIO_WEBCAM_SIOC_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_WEBCAM_PWDN_CTR)            D_GPIO_WEBCAM_PWDN_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_CSO_CTR)   D_GPIO_FUNCTION_SDCARD_VSPI_CSO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_CLK_CTR)   D_GPIO_FUNCTION_SDCARD_VSPI_CLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_MOSI_CTR)  D_GPIO_FUNCTION_SDCARD_VSPI_MOSI_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_VSPI_MISO_CTR)  D_GPIO_FUNCTION_SDCARD_VSPI_MISO_CTR;

DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_CSO_CTR)   D_GPIO_FUNCTION_SDCARD_HSPI_CSO_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_CLK_CTR)   D_GPIO_FUNCTION_SDCARD_HSPI_CLK_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_MOSI_CTR)  D_GPIO_FUNCTION_SDCARD_HSPI_MOSI_CTR;
DEFINE_PGM_CTR(PM_GPIO_FUNCTION_SDCARD_HSPI_MISO_CTR)  D_GPIO_FUNCTION_SDCARD_HSPI_MISO_CTR;

#endif


#define GPIO_ANY           32   // Any GPIO


/**
 * @brief Enum list defining all GPIO functions that is fixed, unique and non changing across builds and hardware
 * @note This list will always be created in its full form
 * @note INV = Inverted pin, low/ground is active
 * @note NP  = No pullup/down 
 * @note Never add `#ifdef` into this enum, as I want all GPIO to always exist and be static for long term debug. `ifdef` should be considered around nicelist
 * @note PD = Pulled down (hardware dependant)
 */
enum GPIO_COMPLETE_STATIC_LIST_IDS  {
  // Default for unused
  GPIO_NONE,
  GPIO_ANALOG, // basic analog that any enabled modules can use on the esp8266, this will need changed to be numbers so esp8266 defaults to 1 and esp32 cna use them all
  // DHT11/22 pins (enabled auto detect?)
  GPIO_DHT11_1, GPIO_DHT11_2,
  // DHT22
  GPIO_DHT22_1, GPIO_DHT22_2,
  // DallasTemperaure 1-wire sensor
  GPIO_DSB_1, GPIO_DSB_2,
  // I2C1
  GPIO_I2C_SCL, GPIO_I2C_SDA,
  GPIO_I2C_SCL2, GPIO_I2C_SDA2,
  // With IC connects that need to be set high/low when unused for stability eg level shifters
  GPIO_UNUSED_FORCED_HIGH,
  GPIO_UNUSED_FORCED_LOW,  
  // IR Transceiver
  GPIO_IRSEND, GPIO_IRRECV,
  // Switches = 8. User connected external switches (No longer using offset, making discrete options)

  // Normal switches
  GPIO_SWT1, GPIO_SWT2, GPIO_SWT3, GPIO_SWT4, GPIO_SWT5, GPIO_SWT6, GPIO_SWT7, GPIO_SWT8,
  GPIO_SWT9, GPIO_SWT10, GPIO_SWT11, GPIO_SWT12, GPIO_SWT13, GPIO_SWT14, GPIO_SWT15, GPIO_SWT16,
  GPIO_SWT17, GPIO_SWT18, GPIO_SWT19, GPIO_SWT20, GPIO_SWT21, GPIO_SWT22, GPIO_SWT23, GPIO_SWT24,
  GPIO_SWT25, GPIO_SWT26, GPIO_SWT27, GPIO_SWT28, GPIO_SWT29, GPIO_SWT30, GPIO_SWT31, GPIO_SWT32,
  // Inverted switches
  GPIO_SWT1_INV, GPIO_SWT2_INV, GPIO_SWT3_INV, GPIO_SWT4_INV, GPIO_SWT5_INV, GPIO_SWT6_INV, GPIO_SWT7_INV, GPIO_SWT8_INV,
  GPIO_SWT9_INV, GPIO_SWT10_INV, GPIO_SWT11_INV, GPIO_SWT12_INV, GPIO_SWT13_INV, GPIO_SWT14_INV, GPIO_SWT15_INV, GPIO_SWT16_INV,
  GPIO_SWT17_INV, GPIO_SWT18_INV, GPIO_SWT19_INV, GPIO_SWT20_INV, GPIO_SWT21_INV, GPIO_SWT22_INV, GPIO_SWT23_INV, GPIO_SWT24_INV,
  GPIO_SWT25_INV, GPIO_SWT26_INV, GPIO_SWT27_INV, GPIO_SWT28_INV, GPIO_SWT29_INV, GPIO_SWT30_INV, GPIO_SWT31_INV, GPIO_SWT32_INV,
  // Non-pull switches
  GPIO_SWT1_NP, GPIO_SWT2_NP, GPIO_SWT3_NP, GPIO_SWT4_NP, GPIO_SWT5_NP, GPIO_SWT6_NP, GPIO_SWT7_NP, GPIO_SWT8_NP,
  GPIO_SWT9_NP, GPIO_SWT10_NP, GPIO_SWT11_NP, GPIO_SWT12_NP, GPIO_SWT13_NP, GPIO_SWT14_NP, GPIO_SWT15_NP, GPIO_SWT16_NP,
  GPIO_SWT17_NP, GPIO_SWT18_NP, GPIO_SWT19_NP, GPIO_SWT20_NP, GPIO_SWT21_NP, GPIO_SWT22_NP, GPIO_SWT23_NP, GPIO_SWT24_NP,
  GPIO_SWT25_NP, GPIO_SWT26_NP, GPIO_SWT27_NP, GPIO_SWT28_NP, GPIO_SWT29_NP, GPIO_SWT30_NP, GPIO_SWT31_NP, GPIO_SWT32_NP,
  // Inverted non-pull switches
  GPIO_SWT1_INV_NP, GPIO_SWT2_INV_NP, GPIO_SWT3_INV_NP, GPIO_SWT4_INV_NP, GPIO_SWT5_INV_NP, GPIO_SWT6_INV_NP, GPIO_SWT7_INV_NP, GPIO_SWT8_INV_NP,
  GPIO_SWT9_INV_NP, GPIO_SWT10_INV_NP, GPIO_SWT11_INV_NP, GPIO_SWT12_INV_NP, GPIO_SWT13_INV_NP, GPIO_SWT14_INV_NP, GPIO_SWT15_INV_NP, GPIO_SWT16_INV_NP,
  GPIO_SWT17_INV_NP, GPIO_SWT18_INV_NP, GPIO_SWT19_INV_NP, GPIO_SWT20_INV_NP, GPIO_SWT21_INV_NP, GPIO_SWT22_INV_NP, GPIO_SWT23_INV_NP, GPIO_SWT24_INV_NP,
  GPIO_SWT25_INV_NP, GPIO_SWT26_INV_NP, GPIO_SWT27_INV_NP, GPIO_SWT28_INV_NP, GPIO_SWT29_INV_NP, GPIO_SWT30_INV_NP, GPIO_SWT31_INV_NP, GPIO_SWT32_INV_NP,

  // Buttons
  GPIO_KEY1, GPIO_KEY2, GPIO_KEY3, GPIO_KEY4, GPIO_KEY5, GPIO_KEY6, GPIO_KEY7, GPIO_KEY8,
  GPIO_KEY9, GPIO_KEY10, GPIO_KEY11, GPIO_KEY12, GPIO_KEY13, GPIO_KEY14, GPIO_KEY15, GPIO_KEY16,
  GPIO_KEY17, GPIO_KEY18, GPIO_KEY19, GPIO_KEY20, GPIO_KEY21, GPIO_KEY22, GPIO_KEY23, GPIO_KEY24,
  GPIO_KEY25, GPIO_KEY26, GPIO_KEY27, GPIO_KEY28, GPIO_KEY29, GPIO_KEY30, GPIO_KEY31, GPIO_KEY32,
  // Inverted keys
  GPIO_KEY1_INV, GPIO_KEY2_INV, GPIO_KEY3_INV, GPIO_KEY4_INV, GPIO_KEY5_INV, GPIO_KEY6_INV, GPIO_KEY7_INV, GPIO_KEY8_INV,
  GPIO_KEY9_INV, GPIO_KEY10_INV, GPIO_KEY11_INV, GPIO_KEY12_INV, GPIO_KEY13_INV, GPIO_KEY14_INV, GPIO_KEY15_INV, GPIO_KEY16_INV,
  GPIO_KEY17_INV, GPIO_KEY18_INV, GPIO_KEY19_INV, GPIO_KEY20_INV, GPIO_KEY21_INV, GPIO_KEY22_INV, GPIO_KEY23_INV, GPIO_KEY24_INV,
  GPIO_KEY25_INV, GPIO_KEY26_INV, GPIO_KEY27_INV, GPIO_KEY28_INV, GPIO_KEY29_INV, GPIO_KEY30_INV, GPIO_KEY31_INV, GPIO_KEY32_INV,
  // Non-pull keys
  GPIO_KEY1_NP, GPIO_KEY2_NP, GPIO_KEY3_NP, GPIO_KEY4_NP, GPIO_KEY5_NP, GPIO_KEY6_NP, GPIO_KEY7_NP, GPIO_KEY8_NP,
  GPIO_KEY9_NP, GPIO_KEY10_NP, GPIO_KEY11_NP, GPIO_KEY12_NP, GPIO_KEY13_NP, GPIO_KEY14_NP, GPIO_KEY15_NP, GPIO_KEY16_NP,
  GPIO_KEY17_NP, GPIO_KEY18_NP, GPIO_KEY19_NP, GPIO_KEY20_NP, GPIO_KEY21_NP, GPIO_KEY22_NP, GPIO_KEY23_NP, GPIO_KEY24_NP,
  GPIO_KEY25_NP, GPIO_KEY26_NP, GPIO_KEY27_NP, GPIO_KEY28_NP, GPIO_KEY29_NP, GPIO_KEY30_NP, GPIO_KEY31_NP, GPIO_KEY32_NP,
  // Inverted non-pull keys (1 to 8)
  GPIO_KEY1_INV_NP, GPIO_KEY2_INV_NP, GPIO_KEY3_INV_NP, GPIO_KEY4_INV_NP, GPIO_KEY5_INV_NP, GPIO_KEY6_INV_NP, GPIO_KEY7_INV_NP, GPIO_KEY8_INV_NP,
  GPIO_KEY9_INV_NP, GPIO_KEY10_INV_NP, GPIO_KEY11_INV_NP, GPIO_KEY12_INV_NP, GPIO_KEY13_INV_NP, GPIO_KEY14_INV_NP, GPIO_KEY15_INV_NP, GPIO_KEY16_INV_NP,
  GPIO_KEY17_INV_NP, GPIO_KEY18_INV_NP, GPIO_KEY19_INV_NP, GPIO_KEY20_INV_NP, GPIO_KEY21_INV_NP, GPIO_KEY22_INV_NP, GPIO_KEY23_INV_NP, GPIO_KEY24_INV_NP,
  GPIO_KEY25_INV_NP, GPIO_KEY26_INV_NP, GPIO_KEY27_INV_NP, GPIO_KEY28_INV_NP, GPIO_KEY29_INV_NP, GPIO_KEY30_INV_NP, GPIO_KEY31_INV_NP, GPIO_KEY32_INV_NP,
  // Touch keys (1 to 8)
  GPIO_KEY1_TOUCH, GPIO_KEY2_TOUCH, GPIO_KEY3_TOUCH, GPIO_KEY4_TOUCH, GPIO_KEY5_TOUCH, GPIO_KEY6_TOUCH, GPIO_KEY7_TOUCH, GPIO_KEY8_TOUCH,
  GPIO_KEY9_TOUCH, GPIO_KEY10_TOUCH, GPIO_KEY11_TOUCH, GPIO_KEY12_TOUCH, GPIO_KEY13_TOUCH, GPIO_KEY14_TOUCH, GPIO_KEY15_TOUCH, GPIO_KEY16_TOUCH,
  GPIO_KEY17_TOUCH, GPIO_KEY18_TOUCH, GPIO_KEY19_TOUCH, GPIO_KEY20_TOUCH, GPIO_KEY21_TOUCH, GPIO_KEY22_TOUCH, GPIO_KEY23_TOUCH, GPIO_KEY24_TOUCH,
  GPIO_KEY25_TOUCH, GPIO_KEY26_TOUCH, GPIO_KEY27_TOUCH, GPIO_KEY28_TOUCH, GPIO_KEY29_TOUCH, GPIO_KEY30_TOUCH, GPIO_KEY31_TOUCH, GPIO_KEY32_TOUCH,


  //unknown button options?
  GPIO_CNTR1, GPIO_CNTR2, GPIO_CNTR3, GPIO_CNTR4,
  GPIO_CNTR1_NP, GPIO_CNTR2_NP, GPIO_CNTR3_NP, GPIO_CNTR4_NP,
  // Relays
  GPIO_REL1, GPIO_REL2, GPIO_REL3, GPIO_REL4, GPIO_REL5, GPIO_REL6, GPIO_REL7, GPIO_REL8,
  GPIO_REL1_INV, GPIO_REL2_INV, GPIO_REL3_INV, GPIO_REL4_INV, GPIO_REL5_INV, GPIO_REL6_INV, GPIO_REL7_INV, GPIO_REL8_INV,
  // PWM 2023: PWM Channels are no longer part of lighting
  GPIO_PWM1, GPIO_PWM2, GPIO_PWM3, GPIO_PWM4, GPIO_PWM5,
  GPIO_PWM1_INV, GPIO_PWM2_INV, GPIO_PWM3_INV, GPIO_PWM4_INV, GPIO_PWM5_INV,
  // LEDs
  GPIO_LED1,     GPIO_LED2,     GPIO_LED3,     GPIO_LED4,     GPIO_LED5,     GPIO_LED6,     GPIO_LED7,     GPIO_LED8,
  GPIO_LED1_INV, GPIO_LED2_INV, GPIO_LED3_INV, GPIO_LED4_INV, GPIO_LED5_INV, GPIO_LED6_INV, GPIO_LED7_INV, GPIO_LED8_INV,
  // MH-Z19 Serial interface
  GPIO_MHZ_TXD, GPIO_MHZ_RXD,
  // SenseAir Serial interface
  GPIO_SAIR_TX, GPIO_SAIR_RX,
  // SPI Chip Select, SPI Data Direction
  GPIO_SPI_CS, GPIO_SPI_DC,
  // Serial Bridge Serial interface
  GPIO_SBR_TX, GPIO_SBR_RX,
  // SR04 ultrasonic
  GPIO_SR04_TRIG, GPIO_SR04_ECHO,

  // mHLK_LD2410
  GPIO_LD2410_RX, GPIO_LD2410_TX,


  // Rotary Encoder (e.g. LPD3806-360BM-G5-24C)
  GPIO__ROTARY_ENCODER_A_, GPIO__ROTARY_ENCODER_B_,
  // LDR Basic
  GPIO_LDR_BASIC_DIGITAL1, GPIO_LDR_BASIC_ANALOG1,
  GPIO_LDR_BASIC_DIGITAL2, GPIO_LDR_BASIC_ANALOG2,
  // SDMxx interfaces
  GPIO_SDM120_TX, GPIO_SDM120_RX, GPIO_SDM630_TX, GPIO_SDM630_RX,
  // PZEM0XX Serial interface, PZEM004T Serial interface, PZEM-014,016 Serial Modbus interface, PZEM-003,017 Serial Modbus interface 
  GPIO_PZEM0XX_TX, GPIO_PZEM004_RX, GPIO_PZEM0XX_RX_MODBUS, GPIO_PZEM017_RX,
  // HX711 Load Cell
  GPIO_HX711_SCK, GPIO_HX711_DAT,

  GPIO_VL53L0X_XSHUT1,GPIO_VL53L0X_XSHUT2,GPIO_VL53L0X_XSHUT3,GPIO_VL53L0X_XSHUT4,GPIO_VL53L0X_XSHUT5,GPIO_VL53L0X_XSHUT6,GPIO_VL53L0X_XSHUT7,GPIO_VL53L0X_XSHUT8,
  GPIO_VL53L1X_XSHUT1,GPIO_VL53L1X_XSHUT2,GPIO_VL53L1X_XSHUT3,GPIO_VL53L1X_XSHUT4,GPIO_VL53L1X_XSHUT5,GPIO_VL53L1X_XSHUT6,GPIO_VL53L1X_XSHUT7,GPIO_VL53L1X_XSHUT8,


  GPIO_MOISTURE_ANALOG,



  // RF Transceiver
  GPIO_RFSEND, GPIO_RFRECV,
  // Tuya Serial interface
  GPIO_TUYA_TX, GPIO_TUYA_RX,
  // Software SPI (Master Input Slave Output, Master Output Slave Input, Serial Clock, Chip Select, Data or Command)
  GPIO_SSPI_MISO, GPIO_SSPI_MOSI, GPIO_SSPI_SCLK, GPIO_SSPI_CS, GPIO_SSPI_DC,
  // Energy monitor chip = MCP39F501 Serial interface (Shelly2)
  GPIO_MCP39F5_TX, GPIO_MCP39F5_RX, GPIO_MCP39F5_RST,
  // CSE7766 Serial interface (S31 and Pow R2)
  GPIO_CSE7766_TX, GPIO_CSE7766_RX,
  // 433 MHz SAW Radio transceivers  
  GPIO_RF_433MHZ_RX, GPIO_RF_433MHZ_TX,
  // Serial pins (Auto detect hardware vs serial)
  // GPIO_SERIAL_TX, GPIO_SERIAL_RX, //phase out to more specific one below
  GPIO_HWSERIAL0_TX, GPIO_HWSERIAL0_RX,
  GPIO_HWSERIAL1_TX, GPIO_HWSERIAL1_RX,
  GPIO_HWSERIAL2_TX, GPIO_HWSERIAL2_RX,
  GPIO_SWSERIAL0_TX, GPIO_SWSERIAL0_RX,
  // RingBuffers are used on the receive data (PHASE OUT)
  GPIO_HWSERIAL0_RING_BUFFER_TX, GPIO_HWSERIAL0_RING_BUFFER_RX,       // RinfBuffer GPIO should be removed, and instead be a special mode of the serial class. Simply set TX/RX, then with another command enable ringbuffer when desired. 
  GPIO_HWSERIAL1_RING_BUFFER_TX, GPIO_HWSERIAL1_RING_BUFFER_RX,
  GPIO_HWSERIAL2_RING_BUFFER_TX, GPIO_HWSERIAL2_RING_BUFFER_RX,

  GPIO_SERIAL_DEBUG_TX, GPIO_SERIAL_DEBUG_RX,
  // GPS Serial0 on both esp devices (1 of 3)
  GPIO_GPS_SERIAL0_TX, GPIO_GPS_SERIAL0_RX,
  // /**
  //  * @brief MAVLink Decoder
  //  **/
  // GPIO_MAVLINK_DECODER_HWSERIAL0_TX, GPIO_MAVLINK_DECODER_HWSERIAL0_RX,
  // GPIO_MAVLINK_DECODER_HWSERIAL1_TX, GPIO_MAVLINK_DECODER_HWSERIAL1_RX,
  // GPIO_MAVLINK_DECODER_HWSERIAL2_TX, GPIO_MAVLINK_DECODER_HWSERIAL2_RX,
  // /**
  //  * @brief MAVLink Telemetry Passthrough
  //  **/
  // GPIO_MAVLINK_TELEMETRY_HWSERIAL0_TX, GPIO_MAVLINK_TELEMETRY_HWSERIAL0_RX,
  // GPIO_MAVLINK_TELEMETRY_HWSERIAL1_TX, GPIO_MAVLINK_TELEMETRY_HWSERIAL1_RX,
  // GPIO_MAVLINK_TELEMETRY_HWSERIAL2_TX, GPIO_MAVLINK_TELEMETRY_HWSERIAL2_RX,
  // Rotary switch
  GPIO_ROT1A, GPIO_ROT1B, GPIO_ROT2A, GPIO_ROT2B,
  // Motion: PIR
  GPIO_PIR_1, GPIO_PIR_2, GPIO_PIR_3,    GPIO_PIR_4,         //pullup
  GPIO_PIR_1_INV, GPIO_PIR_2_INV, GPIO_PIR_3_INV, GPIO_PIR_4_INV, //pulldown
  // Motion: ? other for later!

  // Arilux RF Receive input
  GPIO_ARIRFRCV, GPIO_ARIRFSEL,
  // Buzzer
  GPIO_BUZZER, GPIO_BUZZER_INV,
  // GPS Serial
  GPIO_GPS_NMEA_RX, GPIO_GPS_NMEA_TX,
  // Basic IO for door closed/lock position
  GPIO_DOOR_LOCK, GPIO_DOOR_OPEN,
  // Nextion Touch panels 
  GPIO_NEXTION_RX, GPIO_NEXTION_TX, GPIO_BACKLIGHT,      // Display backlight control
  GPIO_NEXTION_RX2, GPIO_NEXTION_TX2,      // Serial2 for Nextion
  // Door bell chime (basic relay controls) - // Should be replaced as switch maybe?
  GPIO_CHIME_INPUT, GPIO_CHIME_RINGER,   // Relay silenoid
  // L9110 chip H-brige motor driver
  GPIO_HBRIDGE_L9110_IA, GPIO_HBRIDGE_L9110_IB, GPIO_HBRIDGE_L9110_OA, GPIO_HBRIDGE_L9110_OB, //GPIO_HBRIDGE_ANALOG_SENSE, //analog pin to use for sensing   //change to use anolog sensor class that updates automatically
  // Analog measuring types
  GPIO_ANALOG_POSITION,
  // PC Fan controls using PWM
  GPIO_FAN_PWM1,
  // Shelly 2.5 Energy Sensor with I2C
  GPIO_ADE7953_IRQ,
  // Shelly Dimmer 2 MCU
  GPIO_SHELLY2_SHD_BOOT0, GPIO_SHELLY2_SHD_RESET_INV,
  // ADC options
  GPIO_ADC0_TEMPERATURE,
  //
  GPIO_PULSE_COUNTER,         // 
  GPIO_FAN_IRSEND,        // Calls ceiling fan class to use IR sender
  // Displays
  GPIO_OLED_RESET,
  /**
   * Analog Pins esp32
   * Adding GPIO number here, as ADC number is tied with physical gpio number (not mux'ed)
   * */
  GPIO_ADC1_CH4,
  GPIO_ADC1_CH6,
  GPIO_ADC1_CH7,
  GPIO_ADC1_EXTERNAL_INTERRUPT_TRIGGER,
  /**
   * Special cases
   * */
  GPIO_FUNCTION_RXON_SAMPLING_ENABLED,
  GPIO_FUNCTION_CC1110_SYNC_PULSE_SIGNAL,
  /**
   * @brief Fona Cellular
   **/
  GPIO_FUNCTION__FONA_POWER_KEY_,
  GPIO_FUNCTION__FONA_POWER_STATUS_,
  GPIO_FUNCTION__FONA_NETWORK_STATUS_,
  GPIO_FUNCTION__FONA_RESET_,
  GPIO_FUNCTION__FONA_UART_TX_,
  GPIO_FUNCTION__FONA_UART_RX_,
  GPIO_FUNCTION__FONA_RING_INDICATOR_,
  // Modem
  GPIO_FUNCTION__MODEM_DATA_TERMINAL_READY_DTR_,
  GPIO_FUNCTION__MODEM_TX_,
  GPIO_FUNCTION__MODEM_RX_,
  GPIO_FUNCTION__MODEM_POWER_,
  /**
   * @note All esp32 only options below this point
   * */
  // Webcamera
  GPIO_WEBCAM_XCLK,     // 0       (I)O                GPIO0, CAM_XCLK
  GPIO_WEBCAM_DATA1, GPIO_WEBCAM_DATA2, GPIO_WEBCAM_DATA3, GPIO_WEBCAM_DATA4, GPIO_WEBCAM_DATA5, GPIO_WEBCAM_DATA6, GPIO_WEBCAM_DATA7, GPIO_WEBCAM_DATA8,  // 35      I   NO PULLUP       GPIO35, CAM_DATA8
  GPIO_WEBCAM_PCLK,     // 22      IO      LED         GPIO22, CAM_PCLK
  GPIO_WEBCAM_HREF,     // 23      IO                  GPIO23, CAM_HREF
  GPIO_WEBCAM_VSYNC,    // 25      IO                  GPIO25, CAM_VSYNC
  GPIO_WEBCAM_SIOD,     // 26      IO                  GPIO26, CAM_SIOD
  GPIO_WEBCAM_SIOC,     // 27      IO                  GPIO27, CAM_SIOC
  GPIO_WEBCAM_PWDN,     // 32      IO                  GPIO32, CAM_PWDN
  GPIO_WEBCAM_RESET,
  
  // GPS Serial1 and 2 available on esp32 (2 of 3 ports)
  GPIO_GPS_SERIAL1_TX, GPIO_GPS_SERIAL1_RX,
  GPIO_GPS_SERIAL2_TX, GPIO_GPS_SERIAL2_RX,
  
  /**
   * SD Cards
   * */
  GPIO_FUNCTION_SDCARD_VSPI_CSO, GPIO_FUNCTION_SDCARD_VSPI_CLK, 
  GPIO_FUNCTION_SDCARD_VSPI_MOSI, GPIO_FUNCTION_SDCARD_VSPI_MISO,
  
  GPIO_FUNCTION_SDCARD_HSPI_CSO, GPIO_FUNCTION_SDCARD_HSPI_CLK, 
  GPIO_FUNCTION_SDCARD_HSPI_MOSI, GPIO_FUNCTION_SDCARD_HSPI_MISO,
  
  GPIO_SENSOR_END 
};

// Error as warning to rethink GPIO usage with max 2045
static_assert(GPIO_SENSOR_END < 2000, "Too many UserSelectablePins");


/**
 * @brief Programmer selectable GPIO functionality
 */
enum ProgramSelectablePins {
  GPIO_FIX_START = 2046,
  GPIO_USER=9999,
  GPIO_MAX };


#endif  // mPin_GPIO

