function name = SensorTypeIdToName(id)
% Date Modified: 04 Oct 2025
% SUMMARY:
%   Map unified float sensor type_id (uint8/uint16) → string name using the
%   **exact order** of your enum (starting at 0). Unknown IDs get 'Unknown_<id>'.
%
% ARGUMENTS:
%   id : integer scalar or array
%
% RETURNS:
%   name : string (same size as id)
%
% EXAMPLES:
%   SensorTypeIdToName(0)  % -> "Temperature"
%
% CHANGED:
%   - 04Oct25: initial version (ordered from your enum paste).

% Ordered list matching your C enum (0-based)
persistent TYPE_NAMES
if isempty(TYPE_NAMES)
    TYPE_NAMES = string([ ...
        "Temperature", ...
        "Humidity", ...
        "Pressure", ...
        "GasResistance", ...
        "LightLevel", ...
        "LightLuminance", ...
        "AccelerometerRoll", ...
        "AccelerometerPitch", ...
        "AccelerometerHeading", ...
        "Accelerometer", ...            % x,y,z
        "LinearAcceleration", ...       % x,y,z
        "MagneticField", ...            % x,y,z
        "Orientation", ...              % x,y,z
        "Gyroscope", ...                % x,y,z
        "RotationVector", ...
        "Proximity", ...
        "DistanceCM", ...
        "DistanceMM", ...
        "Distance", ...
        "Latitude", ...
        "Longitude", ...
        "Altitude", ...
        "Speed", ...
        "Voltage", ...
        "Current", ...
        "ActivePower", ...
        "Frequency", ...
        "PowerFactor", ...
        "Energy", ...
        "Gravity", ...
        "Color", ...
        "SunAzimuth", ...
        "SunElevation", ...
        "MagneticFieldUncalibrated", ...
        "GameRotationVector", ...
        "GyroscopeUncalibrated", ...
        "SignificantMotion", ...
        "StepDetector", ...
        "StepCounter", ...
        "GeomagneticRotationVector", ...
        "HeartRate", ...
        "TiltDetector", ...
        "WakeGesture", ...
        "GlanceGesture", ...
        "PickUpGesture", ...
        "Pose6DoF", ...
        "StationaryDetect", ...
        "MotionDetect", ...
        "HeartBeat", ...
        "AccelerometerUncalibrated", ...
        "HingeAngle", ...
        "ADCValue", ...
        "DoorPosition", ...
        "DoorLocked", ...
        "State" ...
        % (Stop before non-float string types; NDJSON contains float 'v')
    ]);
end

% Vectorized mapping
id = double(id);
name = strings(size(id));
maxIdx = numel(TYPE_NAMES)-1;

for k = 1:numel(id)
    if ~isfinite(id(k)) || id(k) < 0 || id(k) > maxIdx
        name(k) = "Unknown_" + string(id(k));
    else
        name(k) = TYPE_NAMES(id(k)+1);
    end
end
end
