
[env:valid__board__esp8266__sonoff_basic_clone_nodemcu]
extends = base_esp8266
board_build.ldscript = ldscripts/pulsar.esp8266.flash.1m0.nofs.ld
build_flags = ${base_esp8266.build_flags}
              -D ESP8266_FLASH_LAYOUT_1M0_NOFS
              -D PULSAR_HAS_FILESYSTEM=0
              -D PULSAR_LEGACY_COMPILED_DEFAULTS_ONLY=1
              -D DISABLE_MODULE_CORE_FILESYSTEM
              -D DEVICE_TESTBED__SONOFF_BASIC_CLONE_NODEMCU
              
              '-DDEVICENAME_CTR="testbed_09__sonoff_nodemcu"'
              '-DDEVICENAME_FRIENDLY_CTR="Socket Basic 01#Roaming"'
              '-DDEVICENAME_ROOMHINT_CTR="Roaming"'
              '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
upload_port = COM21


[env:valid__board__esp8266__shelly_dimmer_clone_nodemcu]
extends = base_esp8266
board_build.ldscript = ldscripts/pulsar.esp8266.flash.1m0.nofs.ld
build_flags = ${base_esp8266.build_flags}
              -D ESP8266_FLASH_LAYOUT_1M0_NOFS
              -D PULSAR_HAS_FILESYSTEM=0
              -D PULSAR_LEGACY_COMPILED_DEFAULTS_ONLY=1
              -D DISABLE_MODULE_CORE_FILESYSTEM
              -D DEVICE_TESTBED__SHELLY_DIMMER_CLONE_NODEMCU
              
              '-DDEVICENAME_CTR="testbed_09__shelly_dimmer_nodemcu"'
              '-DDEVICENAME_FRIENDLY_CTR="Shelly Dimmer Testbed#Roaming"'
              '-DDEVICENAME_ROOMHINT_CTR="Roaming"'
              '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
upload_port = COM21
; upload_port = 192.168.2.141
; upload_port = testbed-09--sonoff-nodemcu.local
; upload_protocol = espota
; extra_scripts = gzip_fw.py
