

[env:tg_hvac_oil_rad01]
extends = env:whitehall_32
build_unflags               = ${esp32_defaults.build_unflags}
build_flags                 = ${esp32_defaults.build_flags}
                                    -D DEVICE_TESTGROUP__HVAC__OIL_RADIATOR_01
                                    -w                                     
lib_extra_dirs          = ${common32.lib_extra_dirs}           
upload_port = 192.168.0.197
; upload_port = c onsumerunit.local
upload_protocol = espota
; upload_port = COM51
; monitor_filters = esp32_exception_decoder
; build_type = debug
