

[platformio]
description = My ESP8266 / ESP32 based devices with Web, MQTT and OTA firmware
src_dir = code
; build_dir = .pioenvs
; boards_dir                  = boards
build_cache_dir = .cache
extra_configs = zplatformio_config/platformio_base.ini
                ; legacy versions below which should move into the above
                platformio_8266.ini
                platformio_32.ini      
                ; Central compiles, should be moved into other well defined files
                zplatformio_override.ini                      
                ; Whitehall 2026
                platformio_whitehall.ini
                ; Meadows 2026
                platformio_meadows.ini
                ; Lighting Testbeds: Added here to declutter everything else
                platformio_lgt.ini
                ; Cellular Enabled
                platformio_cellular.ini
                ; Examples of Common Builds
                platformio_templates.ini
                ; Validations
                platformio_compile_testers.ini
                ; Developing
                platformio_developing.ini
                ; Testbeds
                platformio_testbeds.ini
                ; TestGroups: Cameras
                platformio_tg_cameras.ini
                ; Remote builds (Not in homes)
                platformio_remote.ini
                ; Seasonal builds (Xmas, Halloween, etc)S
                platformio_seasonal.ini
                ; add groups
                build_env_groups/*.ini
default_envs =  ${build_envs.default_envs}



; base_esp32
;     normal 2-slot OTA
;     ~2 MB / ~2 MB

; base_esp32_large_app
;     single large app
;     no OTA/recovery
;     maximum flash for bench/special cases

; base_esp32_safeboot
;     small recovery partition
;     large main PulSar partition