
; ;;; HOME INSTALLED ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
; Adding a new developing ini. This means anything in the others, should be distilled to functional, testing, anything that will be reused at regular intervals. 
; Developing, is all testbeds, partial builds, things that may be deleted.


; ;;; ESP8266 Home Default ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;    maybe add wifi in here? SSIDs etc?
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
[env:testbed_82]
platform = ${common.platform}
platform_packages = ${common.platform_packages}
framework = ${common.framework}
board = ${common.board}
board_build.ldscript  = ${common.board_build.ldscript}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.f_flash = ${common.board_build.f_flash}
board_build.f_cpu = ${common.board_build.f_cpu}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}
                                -D USER_MICHAEL
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
upload_resetmethod = ${common.upload_resetmethod}
upload_speed = ${common.upload_speed}
extra_scripts = ${common.extra_scripts}
lib_extra_dirs = ${common.lib_extra_dirs}
lib_ldf_mode = chain
; lib_deps = ${common.lib_deps}

; ;;; ESP32 Home Default ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 

[env:testbed_32]
extends                 = common32
framework               = ${common.framework}
platform                = ${common32.platform}
platform_packages       = ${common32.platform_packages}
board                   = ${common32.board}
board_build.ldscript    = ${common32.board_build.ldscript}
board_build.partitions  = ${common32.board_build.partitions}
board_build.flash_mode  = ${common32.board_build.flash_mode}
board_build.f_flash     = ${common32.board_build.f_flash}
board_build.f_cpu       = ${common32.board_build.f_cpu}
monitor_speed           = ${common32.monitor_speed}
upload_port             = ${common32.upload_port}
upload_resetmethod      = ${common32.upload_resetmethod}
upload_speed            = ${common32.upload_speed}
extra_scripts           = ${common32.extra_scripts}
build_unflags           = ${common32.build_unflags}
build_flags             = ${common32.build_flags}
                            -D USE_USER_MICHAEL
                            '-DSTA_SSID1="Aurora2400"'
                            '-DSTA_PASS1="af4d8bc9ab"'
lib_extra_dirs          = ${common32.lib_extra_dirs}
lib_ldf_mode = chain
lib_deps = ${common.lib_deps}
lib_ignore              =
    cc1101
    ESP32 Azure IoT Arduino
    ESP32 Async UDP
    ESP32 BLE Arduino
    SimpleBLE
    NetBIOS
    Preferences
    BluetoothSerial


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 


[env:testbed_01__sensors_nextion]
extends = env:testbed_32
build_flags = ${common.build_flags} -w
                    -D DEVICE_TESTBED_01__SENSORS_NEXTION
                    -D FIRMWARE_DEFAULT__LIGHTING_CONFIG__COMPLETE
                    ; -D ENABLE_FEATURE_LIGHTING__DISABLE_WEBPAGE_TO_REDUCE_MEMORY_USAGE
                    ; -D ENABLE_DEBUGFEATURE_TASKER__DEBUG_MEMORY_PER_MODULE
                    ; -D ENABLE_FEATURE_DEBUG_TASKER_INTERFACE_PERFORMANCE
                    -D USE_USER_MICHAEL            
                    '-DDEVICENAME_CTR="testbed_01__sensors_nextion"'
                    '-DDEVICENAME_FRIENDLY_CTR="testbed_01__sensors_nextion#Office"'
                    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
                    ; -Wl,-Map,firmware.map
                    ; -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
;                     -Wl,-Map,firmware_inspect.map
;                     ; ,_printf_float
;                     ; 1) lie about max app size so build won't be blocked
; board_upload.maximum_size = 3145728  ; 3MB (pick anything > your current .bin)
; ; 2) use a partitions CSV with a bigger app slot
; board_build.partitions = partitions_inspect.csv
; ; 3) (optional) lie about flash size (only for this env)
; board_upload.flash_size = 4MB
; board_build.flash_size  = 4MB
lib_extra_dirs = ${common32.lib_extra_dirs}
upload_protocol = espota
upload_port = 192.168.2.140
; upload_port = testbed-01--sensors-nextion.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
; upload_port = COM37



[env:testbed_02__motion_audio]
extends = env:testbed_32
platform = espressif32@5.3.0
platform_packages =   platformio/framework-arduinoespressif32 @ 3.20005.220925
board_build.ldscript =
board_build.partitions  = partitions/esp32_partition_4MB_app1984k_fs64k.csv
; extra_scripts = post:tools/post_copy_artifacts.py
build_flags = ${common.build_flags} -w
                    -D DEVICE_TESTBED_02__MOTION_AUDIO
                    ; -D FIRMWARE_DEFAULT__LIGHTING_CONFIG__COMPLETE
                    -D USE_USER_MICHAEL            
                    -D USE_DEBUGFEATURE__TOF_VL53L1X__TEMPORARY_FORCE_I2C_START
                    -D I2C_BUS_SPEED=400000
                    '-DDEVICENAME_CTR="testbed_02__motion_audio"'
                    '-DDEVICENAME_FRIENDLY_CTR="testbed_02__motion_audio#Office"'
                    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
                    -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_FULL
                    ; -Wl,-Map,firmware.map
                    ; -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
;                     -Wl,-Map,firmware_inspect.map
;                     ; ,_printf_float
;                     ; 1) lie about max app size so build won't be blocked
; board_upload.maximum_size = 3145728  ; 3MB (pick anything > your current .bin)
; ; 2) use a partitions CSV with a bigger app slot
; board_build.partitions = partitions_inspect.csv
; ; 3) (optional) lie about flash size (only for this env)
; board_upload.flash_size = 4MB
; board_build.flash_size  = 4MB
lib_extra_dirs = ${common32.lib_extra_dirs}
                lib/lib_filters
                ; lib/lib_tasserial1
                lib/lib_tasserial2
                lib/lib_filters
                lib/lib_wled32
; upload_protocol = espota
; upload_port = 192.168.2.43
; upload_port = testbed-01--sensors-nextion.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM88


[env:testbed_04__hvac_x1]
extends = env:testbed_32
build_flags = ${common.build_flags} -w
                    -D DEVICE_TESTBED_04__HVAC_X1
                    -D USE_USER_MICHAEL            
                    '-DDEVICENAME_CTR="testbed_04__hvac_x1"'
                    '-DDEVICENAME_FRIENDLY_CTR="testbed_04__hvac_x1#Office"'
                    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
                    '-DDEVICENAME_ROOMHINT_CTR="Roaming"'
                    ; -Wl,-Map,firmware.map
                    ; -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
;                     -Wl,-Map,firmware_inspect.map
;                     ; ,_printf_float
;                     ; 1) lie about max app size so build won't be blocked
; board_upload.maximum_size = 3145728  ; 3MB (pick anything > your current .bin)
; ; 2) use a partitions CSV with a bigger app slot
; board_build.partitions = partitions_inspect.csv
; ; 3) (optional) lie about flash size (only for this env)
; board_upload.flash_size = 4MB
; board_build.flash_size  = 4MB
; lib_extra_dirs = ${common32.lib_extra_dirs}
upload_protocol = espota
upload_port = 192.168.2.150
; upload_port = testbed-04--hvac-x1.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
; upload_port = COM20



[env:testbed_05__switch_button]
extends = env:whitehall_32
platform = espressif32@5.3.0
platform_packages =   platformio/framework-arduinoespressif32 @ 3.20005.220925
board_build.ldscript =
build_unflags = -Wall -Wextra -Werror
build_flags       = ${common.build_flags} 
                -D DEVICE_TESTBED_05__SWITCHES_BUTTONS
                -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_FULL
                -w
                -Wno-packed-bitfield-compat
                -D USE_USER_MICHAEL    
                '-DDEVICENAME_CTR="testbed_05__switch_button"'
                '-DDEVICENAME_FRIENDLY_CTR="testbed_05__switch_button#Testbed"'
                '-DMQTT_HOST="192.168.3.70"'
; upload_port = COM53
upload_protocol = espota
; upload_port = 192.168.0.28
upload_port = testbed-05--switch-button.local





[env:testbed_06__gps_decoder]
extends = env:testbed_32
platform = espressif32@5.3.0
platform_packages =   platformio/framework-arduinoespressif32 @ 3.20005.220925
board_build.ldscript =
board_build.partitions  = partitions/esp32_partition_4MB_app1984k_fs64k.csv
; extra_scripts = post:tools/post_copy_artifacts.py
build_flags = ${common.build_flags} -w
                    -Wall
                    -Wno-packed-bitfield-compat
                    -D DEVICE_TESTBED_06__GPS_DECODER_WITH_SERIAL_SNIFFERS
                    ; -D FIRMWARE_DEFAULT__LIGHTING_CONFIG__COMPLETE
                    -D USE_USER_MICHAEL            
                    -D USE_DEBUGFEATURE__TOF_VL53L1X__TEMPORARY_FORCE_I2C_START
                    -D I2C_BUS_SPEED=400000
                    '-DDEVICENAME_CTR="testbed_06__gps_decoder"'
                    '-DDEVICENAME_FRIENDLY_CTR="testbed_06__gps_decoder#Office"'
                    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
                    -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_FULL
                    -D ENABLE_FEATURE__MQTT_ENABLE_SENDING_LIMIT_MS=100
                    ; -Wl,-Map,firmware.map
                    ; -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
;                     -Wl,-Map,firmware_inspect.map
;                     ; ,_printf_float
;                     ; 1) lie about max app size so build won't be blocked
; board_upload.maximum_size = 3145728  ; 3MB (pick anything > your current .bin)
; ; 2) use a partitions CSV with a bigger app slot
; board_build.partitions = partitions_inspect.csv
; ; 3) (optional) lie about flash size (only for this env)
; board_upload.flash_size = 4MB
; board_build.flash_size  = 4MB
lib_extra_dirs = ${common32.lib_extra_dirs}
                lib/lib_filters
                ; lib/lib_tasserial1
                lib/lib_tasserial2
                lib/lib_filters
                lib/lib_wled32
                lib/lib_streamdebugger
                ; lib/lib_gps
; upload_protocol = espota
; upload_port = 192.168.2.63
; upload_port = testbed-01--sensors-nextion.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM20


[env:testbed_06__gps_decoder_02]
extends = env:testbed_32
platform = espressif32@5.3.0
platform_packages =   platformio/framework-arduinoespressif32 @ 3.20005.220925
board_build.ldscript =
board_build.partitions  = partitions/esp32_partition_4MB_app1984k_fs64k.csv
; extra_scripts = post:tools/post_copy_artifacts.py
build_flags = ${common.build_flags} -w
                    -Wall
                    -Wno-packed-bitfield-compat
                    -D DEVICE_TESTBED_06__GPS_DECODER_WITH_SERIAL_SNIFFERS
                    ; -D FIRMWARE_DEFAULT__LIGHTING_CONFIG__COMPLETE
                    -D USE_USER_MICHAEL            
                    -D USE_DEBUGFEATURE__TOF_VL53L1X__TEMPORARY_FORCE_I2C_START
                    -D I2C_BUS_SPEED=400000
                    '-DDEVICENAME_CTR="testbed_06__gps_decoder_02"'
                    '-DDEVICENAME_FRIENDLY_CTR="testbed_06__gps_decoder_02#Office"'
                    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
                    -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_FULL
                    ; -D ENABLE_FEATURE__MQTT_ENABLE_SENDING_LIMIT_MS=0
                    ; -Wl,-Map,firmware.map
                    ; -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
;                     -Wl,-Map,firmware_inspect.map
;                     ; ,_printf_float
;                     ; 1) lie about max app size so build won't be blocked
; board_upload.maximum_size = 3145728  ; 3MB (pick anything > your current .bin)
; ; 2) use a partitions CSV with a bigger app slot
; board_build.partitions = partitions_inspect.csv
; ; 3) (optional) lie about flash size (only for this env)
; board_upload.flash_size = 4MB
; board_build.flash_size  = 4MB
lib_extra_dirs = ${common32.lib_extra_dirs}
                lib/lib_filters
                ; lib/lib_tasserial1
                lib/lib_tasserial2
                lib/lib_filters
                lib/lib_wled32
                lib/lib_streamdebugger
                ; lib/lib_gps
upload_protocol = espota
upload_port = 192.168.2.34
; upload_port = testbed-01--sensors-nextion.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
; upload_port = COM16



