
; ;;; HOME INSTALLED temporarily only for me ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 


[env:wht_rgbdesk]
extends = env:whitehall_82
build_flags = ${common.build_flags} -D DEVICE_RGBDESK -w
                    -D USE_USER_MICHAEL
upload_protocol = espota
extra_scripts             =   gzip_fw.py
upload_port = 192.168.0.151
; monitor_filters = esp8266_exception_decoder
; build_type = debug
; upload_port = COM9








[env:dev_desksensor]
extends = env:whitehall_32
build_flags = ${common.build_flags} -D DEVICE_DESKSENSOR -w
                    -D USE_USER_MICHAEL            
                    -DUSE_LIGHTING_TEMPLATE__PALETTE_TESTING_METAL
                    ; -DCORE_DEBUG_LEVEL=5         
lib_extra_dirs  = ${library.lib_extra_dirs}
                
                lib/libesp32
                lib/lib_basic
                lib/lib_wled32
                lib/lib_custom
                
                
                lib/lib_basic
                lib/lib_network
                lib/lib_display
                lib/lib_onewire2023 
                lib/lib_sensor
                lib/lib_nextion_esp32_web
                lib/lib_async32
                lib/libesp32/network
                lib/lib_network_web
                lib/lib_i2c
                lib/lib_default
                lib/lib_energy
                lib/lib_neopixel_april23
                lib/lib_tinygsm

; upload_protocol = espota
; upload_port = 192.168.0.92
; upload_port = desksensor.local
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM27
;${common32.lib_extra_dirs}    




[env:wh_dr0]
extends = env:whitehall_32
build_flags = ${common.build_flags} -D DEVICE_DESKSENSOR_SLAVE_01 -w
                    -D USE_USER_MICHAEL            
                    ; -DCORE_DEBUG_LEVEL=5         
lib_extra_dirs  = lib/libesp32
                lib/lib_basic
                lib/lib_network
                lib/lib_display
                lib/lib_onewire2023 
                lib/lib_sensor
                
                ; 
; upload_protocol = espota
; upload_port = 192.168.0.79
; upload_port = desksensor.local
monitor_filters = esp32_exception_decoder
build_type = debug
upload_port = COM5
;${common32.lib_extra_dirs}    
