
[env:tb_celullar__lilygo_sim7000g_01]
extends = env:meadows_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_CELLULAR__LILYGO_SIM7000G__LOCATOR_01           
                            ; -D ENABLE_ADVANCED_DEBUGGING
                            ; -D ENABLE_DEBUG_FUNCTION_NAMES
                            ; -D ENABLE_IMMEDIATE_BOOT_SERIAL_PRINT_WHILE
                            ; -D ENABLE_DEBUG_LINE_HERE3
                            ; -D ENABLE_DEBUGFEATURE_TIME__SHOW_UPTIME_EVERY_SECOND
                            -D DEBUG_NEWORK_MQTT
                            -w                       
                            '-DDEVICENAME_CTR="cellular_locator_01"'
                            '-DDEVICENAME_FRIENDLY_CTR="cellular_locator_01#Office"'
                            '-DDEVICENAME_DESCRIPTION_CTR="Primary development of active sim card"'
                            '-DDEVICENAME_BUILD_ENVIRONMENT="tb_celullar__lilygo_sim7000g_01"'
lib_extra_dirs = lib/libesp32
                lib/lib_wled32
                lib/lib_tinygsm
                lib/lib_irremote
                lib/libesp32/network
                lib/lib_network_test
                lib/lib_async32
                lib/lib_streamdebugger
                lib/lib_gps
                lib/lib_i2c
                lib/lib_energy
                lib/lib_network_web
                lib/lib_default
                lib/libesp32/network
                lib/libesp32
                lib/lib_basic
                lib/lib_network
                lib/lib_display
                lib/lib_onewire2023 
                lib/lib_sensor  
                lib/lib_custom
                lib/lib_nextion_esp32_web
                lib/lib_tasserial2
; monitor_filters = esp32_exception_decoder
; build_type = debug
; upload_port = COM19
upload_protocol = espota
; upload_port = 192.168.2.72
upload_port = cellular-locator-01.local
; extra_scripts   = ${scripts_defaults.extra_scripts} 
; gzip_fw.py



[env:tb_esp32_sim7000g]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_LILYGO_SIM7000G
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM33
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py



[env:tb_esp32_sim7000g_v2]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_LILYGO_SIM7000G_V2
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM38
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py


[env:tb_cellular_locator_01]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_CELLULAR_LOCATOR_01
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
monitor_filters = esp32_exception_decoder
build_type = debug
upload_port = COM38
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py

[env:tb_multi_cellular_locator_01]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_CELLULAR_LOCATOR_MULTI_FLASH_01
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_tinygsm
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM17
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py


[env:tb_multi_cellular_locator_02]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_CELLULAR_LOCATOR_MULTI_FLASH_02
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
monitor_filters = esp32_exception_decoder
build_type = debug
upload_port = COM33
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py

[env:tb_multi_cellular_locator_03]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_CELLULAR_LOCATOR_MULTI_FLASH_03
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM49
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py

[env:tb_multi_cellular_locator_04]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_CELLULAR_LOCATOR_MULTI_FLASH_04_MQTT_ON_WIFI
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM5
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py




[env:tb_cellular_locator_02]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_TESTBED_ESP32_LILYGO_SIM7000G_CELLULAR_LOCATOR_02
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM19
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py



[env:tb_cellular2024__gps_locator_9000G_01]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_CELLULAR_LTE__GPS_POSITION_LOCATOR_01__2024
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM13
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py

[env:tb_cellular2024__gps_locator_9000G_02]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_CELLULAR_LTE__GPS_POSITION_LOCATOR_02__ON_SIM9000G_2024
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
upload_port = COM27
; upload_protocol = espota
; upload_port = 192.168.0.41
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py


[env:tb_cellular2024__gps_locator_800L_03]
extends = env:whitehall_32
build_flags             = ${esp32_defaults.build_flags} 
                            -D DEVICE_CELLULAR_LTE__GPS_POSITION_LOCATOR_03__ON_SIM800L_2024
                            -w
lib_extra_dirs = ${common.lib_extra_dirs}
              lib/libesp32
              lib/lib_basic
              lib/lib_network
              
              lib/lib_irremote
              lib/lib_basic
              lib/lib_display
              lib/libesp32/network
              lib/lib_network_test
              lib/lib_network_web
              lib/lib_async32
              lib/lib_tinygsm
              lib/lib_custom
              lib/lib_streamdebugger
              lib/lib_gps
; monitor_speed = 921600
; monitor_filters = esp32_exception_decoder
; build_type = debug
; upload_port = COM13
upload_protocol = espota
upload_port = 192.168.0.218
; extra_scripts   = ${scripts_defaults.extra_scripts} 
;                   gzip_fw.py
