; [platformio]
; src_dir = code

; [env:cm_oiltank_c3]
; platform = espressif32 @ 6.4.0
; board = esp32c3_custom
; framework = arduino

; upload_speed = 115200
; monitor_speed = 115200
; upload_port = COM85
; upload_protocol = esptool

; board_build.flash_mode = dio
; board_build.f_flash = 80000000L
; board_build.f_cpu = 160000000L
; board_build.partitions = partitions/esp32c3_partition_app2880k_fs320k.csv

; board_upload.flash_size = 4MB
; board_upload.maximum_size = 1572864  ; 0x170000

; build_flags =
;   -std=gnu++17
;   -DCONFIG_IDF_TARGET_ESP32C3
;   -DDEVICE_MEADOWS__OUTSIDE__OILTANK
;   -DUSE_USER_MICHAEL
;   '-DDEVICENAME_CTR="outside_oiltank"'
;   '-DDEVICENAME_FRIENDLY_CTR="Outside OilTank#Outside"'
;   '-DDEVICENAME_ROOMHINT_CTR="Outside"'
;   '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
;   -DI2C_BUS_SPEED=400000
;   -DENABLE_DEVFEATURE__ESP32C3
;   -DENABLE_DEBUGFEATURE__OVERIDE_FASTBOOT_DISABLE
;   -DENABLE_ADVANCED_DEBUGGING
;   -w
;   -Wall
;   -Wno-overloaded-virtual
;   -Wno-ambiguous-overload

; build_unflags =
;   -Wswitch-unreachable
;   -Wstringop-overflow
;   -Wincompatible-pointer-types
;   -Wnonnull-compare
;   -fexceptions
;   -fno-lto
;   -Wpointer-arith
;   -std=gnu++11

; lib_ldf_mode = chain+
; lib_extra_dirs =
;   lib/lib_basic
;   lib/lib_network
;   lib/lib_display
;   lib/lib_onewire2023
;   lib/lib_sensor
;   lib/lib_custom
;   lib/;lib/lib_wled32
;   lib/lib_neo_original25
;   lib/lib_i2c
;   lib/lib_energy
;   lib/lib_network_web
;   lib/libesp32
;   lib/lib_default
;   lib/lib_neopixel_june24_ws2805
;   lib/lib_nextion_esp32_web
;   lib/lib_filters
