
; ;;; TEST GROUPS : Cameras ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
;     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Cameras Builds ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;




[env:tg_cam__wroover_01]
board = esp32dev
; board = esp-wrover-kit
platform = espressif32@6.4.0
; framework = arduino
framework = arduino
platform_packages = platformio/framework-arduinoespressif32@3.20011.230801
; upload_protocol = esptool
; upload_port = COM23          ; change as needed
; upload_speed = 460800
upload_port = 192.168.2.78
; build_unflags = -mtarget-align
;     -DARDUINO_VARIANT
board_build.flash_mode = dio
board_build.boot = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.mcu = esp32
board_build.psram = enabled
board_build.partitions = partitions/esp32_default.csv   ; or your custom one
board_build.ldscript =
lib_ignore =
    esp32-camera
lib_ldf_mode = deep+
lib_extra_dirs =
    lib/lib_basic
                            lib/lib_network
                            lib/lib_display 
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/lib_basic
                            lib/lib_wled32
                            lib/lib_custom
                            lib/lib_neo_original25
                            lib/lib_i2c
                            lib/lib_energy
                            ; lib/lib_nextion_esp32_web
                            lib/lib_network_web
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            lib/libesp32
                            lib/lib_custom
                            lib/lib_default
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            ;    
; *** Only disabled for Tasmota minimal and Tasmota light. For all other variants needed!
                            lib/lib_basic
; ; **** I2C devices. Most sensors. Disable only if you dont have ANY I2C device enabled
;                             lib/lib_i2c
                            lib/libesp32/network
                            lib/lib_network
; ; *** Displays. Disable if you dont have any Display activated
;                             lib/lib_display
; ; *** Bear SSL and base64. Disable if you dont have SSL or TLS activated
;                             lib/lib_ssl
; ; *** Audio needs a lot of time to compile. Mostly not used functions. Recommended to disable
;                             lib/lib_audio
; ; *** RF 433 stuff (not RF Bridge). Recommended to disable
;                             lib/lib_rf
; *** Mostly not used functions. Recommended to disable
                            ;; lib/lib_div    
                            lib/lib_onewire2023 
                            lib/lib_sensor
                            lib/lib_custom
                            lib/libesp32
                            lib/lib_basic
                            lib/lib_basic
                            lib/lib_network
                            lib/lib_display
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/lib_custom
                            lib/lib_neopixel_june24_ws2805
                            lib/lib_i2c
                            lib/lib_energy
                            lib/lib_nextion_esp32_web
                            lib/lib_default
                            ; lib/lib_tasserial1 # using tasserial from 2024 
build_flags =
    ; -include sdkconfig.override
    ; -include sdkconfig_wroover.h
    -w
    ; -include sdkconfig_wroover.h
    -D DEVICE_TESTGROUP__CAMERAS__WROOVER_E_LARGE_ESP32_BOARD_01
    ; -D USE_MODULE_DRIVERS__CAMERA
    ; -D CAMERA_MODEL_WROVER_KIT
    -D ENABLE_DEVFEATURE_ANALOG_WRITE_EMULATION_VERSION2
    -D USE_USER_MICHAEL
    -D I2C_BUS_SPEED=400000
    -DBOARD_HAS_PSRAM
    '-DDEVICENAME_CTR="tg_cam__wroover_01"'
    '-DDEVICENAME_FRIENDLY_CTR="TestGroup Camera WROVER-E 01#Testbed"'
    '-DDEVICENAME_DESCRIPTION_CTR="ESP32;WROVER-E;Testbed"'
    '-DMQTT_HOST="192.168.3.70"'
    -D SETTINGS_LOCATION=0x300000
    -D SETTINGS_SIZE=0x10000
    ; -D CORE_DEBUG_LEVEL=5
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D Serial=Serial0
    -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_BASIC
    -D ENABLE_DEBUG_LINE_HERE3
    -D ENABLE_DEBUG_MANUAL_DELAYS
    ; -D ENABLE_DEBUG_SPLASH__PSRAM_USAGE
    -D ENABLE_DEBUGFEATURE_LOGS__FORCE_FLUSH_ON_TRANSMIT
    -D DISABLE_LEDC_DEFINE_TO_PATCH_BUILD_ERROR_JUNE25
    -D ENABLE_IMMEDIATE_BOOT_SERIAL_PRINT_WHILE
    ; -D ENABLE_DEBUGFEATURE_TIME__SHOW_UPTIME_EVERY_SECOND
    -D ENABLE_DEBUG_MODULE_HARDWAREPINS_SUBSECTION_TEMPLATES
    -Ilib/lib_esp32_camera2/driver/private_include
    -Ilib/lib_esp32_camera2/driver/include
    -Ilib/lib_esp32_camera2/conversions
    -I"C:/Users/micha/.platformio/packages/framework-arduinoespressif32/tools/esp32-arduino-libs/esp32/include/esp_hw_support/include"
    -I "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src"
    -I "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SD_MMC/src"



[env:tg_cam__wroover_02]
board = esp32dev
; board = esp-wrover-kit
platform = espressif32@6.4.0
; framework = arduino
framework = arduino
platform_packages = platformio/framework-arduinoespressif32@3.20011.230801
; upload_protocol = esptool
; upload_port = COM23          ; change as needed
; upload_speed = 460800
upload_port = 192.168.2.83
; build_unflags = -mtarget-align
;     -DARDUINO_VARIANT
board_build.flash_mode = dio
board_build.boot = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.mcu = esp32
board_build.psram = enabled
board_build.partitions = partitions/esp32_default.csv   ; or your custom one
board_build.ldscript =
lib_ignore =
    esp32-camera
lib_ldf_mode = deep+
lib_extra_dirs =
    lib/lib_basic
                            lib/lib_network
                            lib/lib_display 
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/lib_basic
                            lib/lib_wled32
                            lib/lib_custom
                            lib/lib_neo_original25
                            lib/lib_i2c
                            lib/lib_energy
                            ; lib/lib_nextion_esp32_web
                            lib/lib_network_web
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            lib/libesp32
                            lib/lib_custom
                            lib/lib_default
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            ;    
; *** Only disabled for Tasmota minimal and Tasmota light. For all other variants needed!
                            lib/lib_basic
; ; **** I2C devices. Most sensors. Disable only if you dont have ANY I2C device enabled
;                             lib/lib_i2c
                            lib/libesp32/network
                            lib/lib_network
; ; *** Displays. Disable if you dont have any Display activated
;                             lib/lib_display
; ; *** Bear SSL and base64. Disable if you dont have SSL or TLS activated
;                             lib/lib_ssl
; ; *** Audio needs a lot of time to compile. Mostly not used functions. Recommended to disable
;                             lib/lib_audio
; ; *** RF 433 stuff (not RF Bridge). Recommended to disable
;                             lib/lib_rf
; *** Mostly not used functions. Recommended to disable
                            ;; lib/lib_div    
                            lib/lib_onewire2023 
                            lib/lib_sensor
                            lib/lib_custom
                            lib/libesp32
                            lib/lib_basic
                            lib/lib_basic
                            lib/lib_network
                            lib/lib_display
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/lib_custom
                            lib/lib_neopixel_june24_ws2805
                            lib/lib_i2c
                            lib/lib_energy
                            lib/lib_nextion_esp32_web
                            lib/lib_default
                            ; lib/lib_tasserial1 # using tasserial from 2024 
build_flags =
    ; -include sdkconfig.override
    ; -include sdkconfig_wroover.h
    -w
    ; -include sdkconfig_wroover.h
    -D DEVICE_TESTGROUP__CAMERAS__WROOVER_E_LARGE_ESP32_BOARD_02
    ; -D USE_MODULE_DRIVERS__CAMERA
    ; -D CAMERA_MODEL_WROVER_KIT
    -D ENABLE_DEVFEATURE_ANALOG_WRITE_EMULATION_VERSION2
    -D USE_USER_MICHAEL
    -D I2C_BUS_SPEED=400000
    -DBOARD_HAS_PSRAM
    '-DDEVICENAME_CTR="tg_cam__wroover_02"'
    '-DDEVICENAME_FRIENDLY_CTR="TestGroup Camera WROVER-E 02#Testbed"'
    '-DDEVICENAME_DESCRIPTION_CTR="ESP32;WROVER-E;Testbed"'
    '-DMQTT_HOST="192.168.3.70"'
    -D SETTINGS_LOCATION=0x300000
    -D SETTINGS_SIZE=0x10000
    ; -D CORE_DEBUG_LEVEL=5
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D Serial=Serial0
    -D FIRMWARE_DEFAULT__INCLUDE_WEBSERVER_BASIC
    -D ENABLE_DEBUG_LINE_HERE3
    -D ENABLE_DEBUG_MANUAL_DELAYS
    ; -D ENABLE_DEBUG_SPLASH__PSRAM_USAGE
    -D ENABLE_DEBUGFEATURE_LOGS__FORCE_FLUSH_ON_TRANSMIT
    -D DISABLE_LEDC_DEFINE_TO_PATCH_BUILD_ERROR_JUNE25
    -D ENABLE_IMMEDIATE_BOOT_SERIAL_PRINT_WHILE
    ; -D ENABLE_DEBUGFEATURE_TIME__SHOW_UPTIME_EVERY_SECOND
    -D ENABLE_DEBUG_MODULE_HARDWAREPINS_SUBSECTION_TEMPLATES
    -Ilib/lib_esp32_camera2/driver/private_include
    -Ilib/lib_esp32_camera2/driver/include
    -Ilib/lib_esp32_camera2/conversions
    -I"C:/Users/micha/.platformio/packages/framework-arduinoespressif32/tools/esp32-arduino-libs/esp32/include/esp_hw_support/include"
    -I "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src"
    -I "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SD_MMC/src"



[env:tg_cam__wroover_03]
board = esp32dev
; board = esp-wrover-kit
platform = espressif32@6.4.0
; framework = arduino
framework = arduino
platform_packages = platformio/framework-arduinoespressif32@3.20011.230801

upload_protocol = esptool
; upload_port = COM90          ; change as needed
; upload_speed = 460800
upload_port = 192.168.0.180

; build_unflags = -mtarget-align
;     -DARDUINO_VARIANT
board_build.flash_mode = dio
board_build.boot = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.mcu = esp32
board_build.psram = enabled

board_build.partitions = partitions/esp32_default.csv   ; or your custom one
board_build.ldscript =
lib_ignore =
    esp32-camera
lib_ldf_mode = chain+
lib_extra_dirs =
    lib/lib_basic
                            lib/lib_network
                            lib/lib_display 
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/lib_basic
                            lib/;lib/lib_wled32
                            lib/lib_custom
                            lib/lib_neo_original25
                            lib/lib_i2c
                            lib/lib_energy
                            ; lib/lib_nextion_esp32_web
                            lib/lib_network_web
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            lib/libesp32
                            lib/lib_custom
                            lib/lib_default
; *** ESP32 lib. ALWAYS needed for ESP32 !!!
                            ;    
; *** Only disabled for Tasmota minimal and Tasmota light. For all other variants needed!
                            lib/lib_basic
; ; **** I2C devices. Most sensors. Disable only if you dont have ANY I2C device enabled
;                             lib/lib_i2c
                            lib/libesp32/network
                            lib/lib_network
; ; *** Displays. Disable if you dont have any Display activated
;                             lib/lib_display
; ; *** Bear SSL and base64. Disable if you dont have SSL or TLS activated
;                             lib/lib_ssl
; ; *** Audio needs a lot of time to compile. Mostly not used functions. Recommended to disable
;                             lib/lib_audio
; ; *** RF 433 stuff (not RF Bridge). Recommended to disable
;                             lib/lib_rf
; *** Mostly not used functions. Recommended to disable
                            ;; lib/lib_div    
                            lib/lib_onewire2023 
                            lib/lib_sensor
                            lib/lib_custom
                            lib/libesp32
                            lib/lib_basic
                            lib/lib_basic
                            lib/lib_network
                            lib/lib_display
                            lib/lib_onewire2023 
                            lib/lib_sensor                          
                            lib/lib_custom
                            lib/;lib/lib_wled32
                            lib/lib_custom
                            lib/lib_neopixel_june24_ws2805
                            lib/lib_i2c
                            lib/lib_energy
                            lib/lib_nextion_esp32_web
                            lib/lib_default
                            ; lib/lib_tasserial1 # using tasserial from 2024 
                            lib/libesp32/rtsp


build_flags =
    -w
    -D DEVICE_TESTGROUP__CAMERAS__WROOVER_E_LARGE_ESP32_BOARD_03
    -D USE_USER_MICHAEL
    -D I2C_BUS_SPEED=400000
    -DBOARD_HAS_PSRAM
    '-DDEVICENAME_CTR="tg_cam__wroover_03"'
    '-DDEVICENAME_FRIENDLY_CTR="TestGroup Camera WROVER-E#Testbed"'
    '-DDEVICENAME_DESCRIPTION_CTR="ESP32;WROVER-E;Testbed"'
    '-DD_MQTTSERVER_IP_ADDRESS_COMMA_DELIMITED="192.168.3.70"'
    -D SETTINGS_LOCATION=0x300000
    -D SETTINGS_SIZE=0x10000
    -D CORE_DEBUG_LEVEL=5
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D Serial=Serial0
    ; -D ENABLE_DEBUG_LINE_HERE3
    -D ENABLE_DEBUG_MANUAL_DELAYS
    -D ENABLE_DEVFEATURE_ANALOG_WRITE_EMULATION_VERSION2
    ; -D ENABLE_DEBUG_SPLASH__PSRAM_USAGE
    -D ENABLE_DEBUGFEATURE_LOGS__FORCE_FLUSH_ON_TRANSMIT
    -D DISABLE_LEDC_DEFINE_TO_PATCH_BUILD_ERROR_JUNE25
    -D ENABLE_IMMEDIATE_BOOT_SERIAL_PRINT_WHILE
    ; -D ENABLE_DEBUGFEATURE_TIME__SHOW_UPTIME_EVERY_SECOND
    -D ENABLE_DEBUG_MODULE_HARDWAREPINS_SUBSECTION_TEMPLATES
    -Ilib/lib_esp32_camera2/driver/private_include
    -Ilib/lib_esp32_camera2/driver/include
    -Ilib/lib_esp32_camera2/conversions
    -I"C:/Users/micha/.platformio/packages/framework-arduinoespressif32/tools/esp32-arduino-libs/esp32/include/esp_hw_support/include"
