#pragma once

#define CONFIG_ESP32_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM 1
#define CONFIG_SPIRAM_BOOT_INIT 1
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 16384
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 32768
#define CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY 1
#define CONFIG_SPIRAM_CACHE_WORKAROUND 1
#define CONFIG_SPIRAM_SPEED_80M 1
#define CONFIG_SPIRAM_TYPE_AUTO 1
#define CONFIG_SPIRAM_SIZE -1
#define CONFIG_SPIRAM_MEMTEST 1
#define CONFIG_HEAP_TASK_TRACKING 1
#define CONFIG_MALLOC_FAILURE_FATAL 1
#define CONFIG_TRACEMEM_RESERVE_DRAM 0
