#include "mFileSystem2.h"

//  xdrv_22_sonoff_ifan.ino - sonoff iFan02 and iFan03 support for Tasmota

#ifdef USE_MODULE_DRIVERS_FILESYSTEM2

const char* mFileSystem::PM_MODULE_DRIVERS_FILESYSTEM2_CTR = D_MODULE_DRIVERS_FILESYSTEM_CTR;
const char* mFileSystem::PM_MODULE_DRIVERS_FILESYSTEM2_FRIENDLY_CTR = D_MODULE_DRIVERS_FILESYSTEM_FRIENDLY_CTR;


#endif // USE_MODULE_DRIVERS_FILESYSTEM2
