#pragma once

/**
 * Interface
 * */

/**
 * AnimatorLight
 * */
#define D_EFFECTS_FUNCTION__SOLID_COLOUR__NAME_CTR      "Solid RGBCCT|Solid" // "Solid Colour"
#define D_EFFECTS_FUNCTION__SLOW_GLOW__NAME_CTR         "Slow Glow|Blend" /// I need to add that no only does it check the individual ones, but also the entire string so this can be used in templates fully
#define D_EFFECTS_FUNCTION__SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_RGBCCT_PALETTE_INDEXED_POSITIONS_01__NAME_CTR "Sun Elevation RGBCCT Solid Palette 01"
#define D_EFFECTS_FUNCTION__SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_RGBCCT_PALETTE_INDEXED_POSITIONS_WITH_AUGMENTED_TRANSITIONS_01__NAME_CTR "Sun Elevation RGBCCT Solid Palette Augmented 01"
#define D_EFFECTS_FUNCTION__SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_CCT_TEMPERATURE_01__NAME_CTR "Sun Elevation CCT Temp 01"
#define D_EFFECTS_FUNCTION__FIREPLACE_1D_01__NAME_CTR "FirePlace01"

#define D_EFFECTS_FUNCTION__STATIC__NAME_CTR                  "Static"
#define D_EFFECTS_FUNCTION__STATIC_PATTERN__NAME_CTR          "Solid Pattern"
#define D_EFFECTS_FUNCTION__TRI_STATIC_PATTERN__NAME_CTR      "Solid Pattern Tri"
#define D_EFFECTS_FUNCTION__BLINK__NAME_CTR                   "Blink"
#define D_EFFECTS_FUNCTION__BREATH__NAME_CTR                  "Breathe"
#define D_EFFECTS_FUNCTION__COLOR_WIPE__NAME_CTR              "Wipe"
#define D_EFFECTS_FUNCTION__COLOR_WIPE_RANDOM__NAME_CTR       "Wipe Random"
#define D_EFFECTS_FUNCTION__RANDOM_COLOR__NAME_CTR            "Random Colors"
#define D_EFFECTS_FUNCTION__COLOR_SWEEP__NAME_CTR             "Sweep"
#define D_EFFECTS_FUNCTION__DYNAMIC__NAME_CTR                 "Dynamic"
#define D_EFFECTS_FUNCTION__RAINBOW__NAME_CTR                 "Colorloop"
#define D_EFFECTS_FUNCTION__RAINBOW_CYCLE__NAME_CTR           "Rainbow"
#define D_EFFECTS_FUNCTION__SCAN__NAME_CTR                    "Scan"
#define D_EFFECTS_FUNCTION__DUAL_SCAN__NAME_CTR               "Scan Dual"
#define D_EFFECTS_FUNCTION__FADE__NAME_CTR                    "Fade"
#define D_EFFECTS_FUNCTION__THEATER_CHASE__NAME_CTR           "Theater"
#define D_EFFECTS_FUNCTION__THEATER_CHASE_RAINBOW__NAME_CTR   "Theater Rainbow"
#define D_EFFECTS_FUNCTION__RUNNING_LIGHTS__NAME_CTR          "Running"
#define D_EFFECTS_FUNCTION__SAW__NAME_CTR                     "Saw"
#define D_EFFECTS_FUNCTION__TWINKLE__NAME_CTR                 "Twinkle"
#define D_EFFECTS_FUNCTION__DISSOLVE__NAME_CTR                "Dissolve"
#define D_EFFECTS_FUNCTION__DISSOLVE_RANDOM__NAME_CTR         "Dissolve Rnd"
#define D_EFFECTS_FUNCTION__SPARKLE__NAME_CTR                 "Sparkle"
#define D_EFFECTS_FUNCTION__FLASH_SPARKLE__NAME_CTR           "Sparkle Dark"
#define D_EFFECTS_FUNCTION__HYPER_SPARKLE__NAME_CTR           "Sparkle+"
#define D_EFFECTS_FUNCTION__STROBE__NAME_CTR                  "Strobe"
#define D_EFFECTS_FUNCTION__STROBE_RAINBOW__NAME_CTR          "Strobe Rainbow"
#define D_EFFECTS_FUNCTION__MULTI_STROBE__NAME_CTR            "Strobe Mega"
#define D_EFFECTS_FUNCTION__BLINK_RAINBOW__NAME_CTR           "Blink Rainbow"
#define D_EFFECTS_FUNCTION__ANDROID__NAME_CTR                 "Android"
#define D_EFFECTS_FUNCTION__CHASE_COLOR__NAME_CTR             "Chase"
#define D_EFFECTS_FUNCTION__CHASE_RANDOM__NAME_CTR            "Chase Random"
#define D_EFFECTS_FUNCTION__CHASE_RAINBOW__NAME_CTR           "Chase Rainbow"
#define D_EFFECTS_FUNCTION__CHASE_FLASH__NAME_CTR             "Chase Flash"
#define D_EFFECTS_FUNCTION__CHASE_FLASH_RANDOM__NAME_CTR      "Chase Flash Rnd"
#define D_EFFECTS_FUNCTION__CHASE_RAINBOW_WHITE__NAME_CTR     "Rainbow Runner"
#define D_EFFECTS_FUNCTION__COLORFUL__NAME_CTR                "Colorful"
#define D_EFFECTS_FUNCTION__TRAFFIC_LIGHT__NAME_CTR           "Traffic Light"
#define D_EFFECTS_FUNCTION__COLOR_SWEEP_RANDOM__NAME_CTR      "Sweep Random"
#define D_EFFECTS_FUNCTION__RUNNING_COLOR__NAME_CTR           "Running 2"
#define D_EFFECTS_FUNCTION__RUNNING_RED_BLUE__NAME_CTR        "Red & Blue"
#define D_EFFECTS_FUNCTION__RUNNING_RANDOM__NAME_CTR          "Stream"
#define D_EFFECTS_FUNCTION__LARSON_SCANNER__NAME_CTR          "Scanner"
#define D_EFFECTS_FUNCTION__COMET__NAME_CTR                   "Lighthouse"
#define D_EFFECTS_FUNCTION__FIREWORKS__NAME_CTR               "Fireworks"
#define D_EFFECTS_FUNCTION__RAIN__NAME_CTR                    "Rain"
#define D_EFFECTS_FUNCTION__MERRY_CHRISTMAS__NAME_CTR         "Merry Christmas"
#define D_EFFECTS_FUNCTION__FIRE_FLICKER__NAME_CTR            "Fire Flicker"
#define D_EFFECTS_FUNCTION__GRADIENT__NAME_CTR                "Gradient"
#define D_EFFECTS_FUNCTION__LOADING__NAME_CTR                 "Loading"
#define D_EFFECTS_FUNCTION__POLICE__NAME_CTR                  "Police"
#define D_EFFECTS_FUNCTION__POLICE_ALL__NAME_CTR              "Police All"
#define D_EFFECTS_FUNCTION__TWO_DOTS__NAME_CTR                "Two Dots"
#define D_EFFECTS_FUNCTION__TWO_AREAS__NAME_CTR               "Two Areas"
#define D_EFFECTS_FUNCTION__CIRCUS_COMBUSTUS__NAME_CTR        "Circus"
#define D_EFFECTS_FUNCTION__HALLOWEEN__NAME_CTR               "Halloween"
#define D_EFFECTS_FUNCTION__TRICOLOR_CHASE__NAME_CTR          "Tri Chase"
#define D_EFFECTS_FUNCTION__TRICOLOR_WIPE__NAME_CTR           "Tri Wipe"
#define D_EFFECTS_FUNCTION__TRICOLOR_FADE__NAME_CTR           "Tri Fade"
#define D_EFFECTS_FUNCTION__LIGHTNING__NAME_CTR               "Lightning"
#define D_EFFECTS_FUNCTION__ICU__NAME_CTR                     "ICU"
#define D_EFFECTS_FUNCTION__MULTI_COMET__NAME_CTR             "Multi Comet"
#define D_EFFECTS_FUNCTION__DUAL_LARSON_SCANNER__NAME_CTR     "Scanner Dual"
#define D_EFFECTS_FUNCTION__RANDOM_CHASE__NAME_CTR            "Stream 2"
#define D_EFFECTS_FUNCTION__OSCILLATE__NAME_CTR               "Oscillate"
#define D_EFFECTS_FUNCTION__PRIDE_2015__NAME_CTR              "Pride 2015"
#define D_EFFECTS_FUNCTION__JUGGLE__NAME_CTR                  "Juggle"
#define D_EFFECTS_FUNCTION__PALETTE__NAME_CTR                 "Palette"
#define D_EFFECTS_FUNCTION__FIRE_2012__NAME_CTR               "Fire 2012"
#define D_EFFECTS_FUNCTION__COLORWAVES__NAME_CTR              "Colorwaves"
#define D_EFFECTS_FUNCTION__BPM__NAME_CTR                     "Bpm"
#define D_EFFECTS_FUNCTION__FILLNOISE8__NAME_CTR              "Fill Noise"
#define D_EFFECTS_FUNCTION__NOISE16_1__NAME_CTR               "Noise 1"
#define D_EFFECTS_FUNCTION__NOISE16_2__NAME_CTR               "Noise 2"
#define D_EFFECTS_FUNCTION__NOISE16_3__NAME_CTR               "Noise 3"
#define D_EFFECTS_FUNCTION__NOISE16_4__NAME_CTR               "Noise 4"
#define D_EFFECTS_FUNCTION__COLORTWINKLE__NAME_CTR            "Colortwinkles"
#define D_EFFECTS_FUNCTION__LAKE__NAME_CTR                    "Lake"
#define D_EFFECTS_FUNCTION__METEOR__NAME_CTR                  "Meteor"
#define D_EFFECTS_FUNCTION__METEOR_SMOOTH__NAME_CTR           "Meteor Smooth"
#define D_EFFECTS_FUNCTION__RAILWAY__NAME_CTR                 "Railway"
#define D_EFFECTS_FUNCTION__RIPPLE__NAME_CTR                  "Ripple"
#define D_EFFECTS_FUNCTION__TWINKLEFOX__NAME_CTR              "Twinklefox"
#define D_EFFECTS_FUNCTION__TWINKLECAT__NAME_CTR              "Twinklecat"
#define D_EFFECTS_FUNCTION__HALLOWEEN_EYES__NAME_CTR          "Halloween Eyes"
#define D_EFFECTS_FUNCTION__SPOTS__NAME_CTR                   "Spots"
#define D_EFFECTS_FUNCTION__SPOTS_FADE__NAME_CTR              "Spots Fade"
#define D_EFFECTS_FUNCTION__GLITTER__NAME_CTR                 "Glitter"
#define D_EFFECTS_FUNCTION__CANDLE__NAME_CTR                  "Candle"
#define D_EFFECTS_FUNCTION__SHIMMERING_PALETTE__NAME_CTR      "Shimmering Palette"
#define D_EFFECTS_FUNCTION__STARBURST__NAME_CTR               "Fireworks Starburst"
#define D_EFFECTS_FUNCTION__EXPLODING_FIREWORKS__NAME_CTR     "Fireworks 1D"
#define D_EFFECTS_FUNCTION__BOUNCINGBALLS__NAME_CTR           "Bouncing Balls"
#define D_EFFECTS_FUNCTION__SINELON__NAME_CTR                 "Sinelon"
#define D_EFFECTS_FUNCTION__SINELON_DUAL__NAME_CTR            "Sinelon Dual"
#define D_EFFECTS_FUNCTION__SINELON_RAINBOW__NAME_CTR         "Sinelon Rainbow"
#define D_EFFECTS_FUNCTION__POPCORN__NAME_CTR                 "Popcorn"
#define D_EFFECTS_FUNCTION__DRIP__NAME_CTR                    "Drip"
#define D_EFFECTS_FUNCTION__PLASMA__NAME_CTR                  "Plasma"
#define D_EFFECTS_FUNCTION__PERCENT__NAME_CTR                 "Percent"
#define D_EFFECTS_FUNCTION__RIPPLE_RAINBOW__NAME_CTR          "Ripple Rainbow"
#define D_EFFECTS_FUNCTION__HEARTBEAT__NAME_CTR               "Heartbeat"
#define D_EFFECTS_FUNCTION__PACIFICA__NAME_CTR                "Pacifica"
#define D_EFFECTS_FUNCTION__CANDLE_MULTI__NAME_CTR            "Candle Multi"
#define D_EFFECTS_FUNCTION__SOLID_GLITTER__NAME_CTR           "Solid Glitter"
#define D_EFFECTS_FUNCTION__SUNRISE__NAME_CTR                 "Sunrise"
#define D_EFFECTS_FUNCTION__PHASED__NAME_CTR                  "Phased"
#define D_EFFECTS_FUNCTION__TWINKLEUP__NAME_CTR               "Twinkleup"
#define D_EFFECTS_FUNCTION__NOISEPAL__NAME_CTR                "Noise Pal"
#define D_EFFECTS_FUNCTION__SINEWAVE__NAME_CTR                "Sine"
#define D_EFFECTS_FUNCTION__PHASEDNOISE__NAME_CTR             "Phased Noise"
#define D_EFFECTS_FUNCTION__FLOW__NAME_CTR                    "Flow"
#define D_EFFECTS_FUNCTION__CHUNCHUN__NAME_CTR                "Chunchun"

#define D_EFFECTS_FUNCTION__SEVEN_SEGMENT_DISPLAY_MANUAL_NUMBER__NAME_CTR "Seven-Segment Manual"

#define D_EFFECTS_FUNCTION__LCD_CLOCK_BASIC_01__NAME_CTR        "Clock Basic 01"

#define D_EFFECTS_FUNCTION__NOTIFICATION_STATIC_ON__NAME_CTR "Notification On"










