[group_meadows]

; ---------------------------------------------------- Group A: Office or safe to go offline ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
regular_intervals_group_a =
    tg_lgt__esp32_matrix_16x16_16fx
    tg_lgt__esp32_matrix_16x16
    tg_lgt__esp32_matrix_32w8h_weight
    tg_lgt__esp32_matrix_8w32h
    tg_lgt__esp32_7segclock
    tg_lgt__esp32_matrix_32w8h
    cm_lgt__esp32_coneV_1D
; ---------------------------------------------------- Group B: Cant sleep with these not working ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
regular_intervals_group_b =
    cm_livingroom__tv
    cm_bed_alarm_light
    cm_kitchen__room_sensor
    cm_kitchen__glass_box 
    cm_hallway__vase_light
    cm_livingroom__pebbles
; ---------------------------------------------------- Group C: Hard to recover, may need physical access ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
regular_intervals_group_c =
    cm_outside__fence_lights
    cm_outside__garage_tree
    cm_bedroom__door_frame
    cm_mbedroom__ambient_sensor
    cm_guest__prusa_sensor
    cm_landing__glass_box
    cm_office__under_desk
    cm_office__sun_pixel_1d
    testbed_01__sensors_nextion
; ---------------------------------------------------- Group D: ESP8266 Higher Risk ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
regular_intervals_group_d =
    ;; esp8266
    cm_socket_basic_01
    cm_airpurifier
    cm_ifan03_03


testbeds =
    testbed_01__sensors_nextion       ; office, on desk
    ; testbed_02__motion_audio
    ; testbed_03__socket_energy_x1      ; roaming, high amp relay with pzem, but not HVAC (monitoring of test devices)
    ; testbed_04__hvac_x1               ; office, but it under the desk for left side, 24/7 use
    ; testbed_04__hvac_x4               ; temp, tester for whitehall heating (will make handmade device, with dual bme, few db, leds for relay sim)
    testbed_05__switch_button         ; temp, just when testing new code
    testbed_06__gps_decoder           ; office, dev board with ublox serial connections (in office window 24/7)
    ; testbed_07__gps_sdlogger          ; office+roaming, gps, lipo, sd card, webui download using the new sdlog buffer (take with me periodically)
    ; testbed_08__networks              ; temp, keep connection, lte and/or wifi, lipo, light sensor?
    testbed_09__sonoff_basic_nodemcu   ; custom pcb, with button, led as relay, emulate sonoff basic flashing (with usb recovery). Validate esp8266 OTA and recovery
    ; testbed_10__audio_devkit          ; office, ali device 
    ; testbed_11__filesystem            ; testing sd card and file system, with webui download of files, and file management (delete, format etc)
    


shelf_lights =
    tg_lgt__esp32_matrix_16x16
    tg_lgt__esp32_matrix_32w8h_weight ; shelf middle/left (32x8 wide)  = health info, just update to keep code valid
    tg_lgt__esp32_matrix_8w32h        ; shelf middle/right (8x32 tall) = 2D testing
    tg_lgt__esp32_matrix_16x16_16fx   ; shelf bottom/left (16x16) = 16 common 1D segment effects together
    tg_lgt__esp32_7segclock           ; shelf bottom/middle (3d print) = 7seg 3d clock    
    tg_lgt__esp32_matrix_32w8h        ; shelf bottom/right (32x8 wide) = text clock    
    cm_lgt__esp32_coneV_1D               ; Both cones will remain in the office as testers, and will be programmable as 2D or 1D (for dense pixel testing)
    cm_lgt__esp32_coneH_1D               ; put 2d coneV here so I can see compiles in 1D above and this ;;


sockets =
  cm_socket_basic_01
  cm_socket_basic_02
  cm_socket_basic_03
  cm_socket_basic_04
  cm_socket_basic_05
  cm_socket_basic_06
  cm_socket_basic_07
  cm_socket_basic_08
  cm_socket_basic_09
  cm_socket_basic_10
  cm_socket_basic_11
  cm_socket_s26_20

  
home_automation = 
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Kitchen
    cm_kitchen__room_sensor
    cm_kitchen__glass_box
    cm_kitchen__green_plant
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Utility
    cm_utility__room_sensor
    cm_utility__clearvase_light
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Hallway
    cm_hallway__bluevase_light
    cm_hallway__room_sensor
    cm_hallway__consumer_unit
    cm_hallway__heating
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Livingroom
    cm_livingroom__pebbles
    cm_livingroom__tv
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Outside
    cm_outside__fence_lights
    cm_outside__garage_tree
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Garage
    cm_garage__room_sensor
    cm_garage__furnace
    cm_treadmill_power
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Masterbedroom
    cm_bedroom__door_frame
    cm_mbedroom__ambient_sensor
    cm_airpurifier
    cm_mbedroom__bedlight
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Bathroom
    cm_bathroom__immersion
    cm_bathroom__radiator
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Guest Room
    cm_guest__prusa_sensor
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Landing
    cm_landing__glass_box
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Office
    cm_socket_basic_01                        ; shelf
    cm_office__under_desk
    cm_office__sun_pixel_1d
    cm_lgt__esp32_coneV_1D
    cm_lgt__esp32_coneH_1D
    cm_lgt__esp32c3_tester
    cm_lgt__esp32s3_tester
    cm_office__doorframe
    testbed_01__sensors_nextion
    cm_office__rgbww_vertical
    cm_office__ws2815panel12v
    tg_lgt__esp32s3_12v_generic_01
    cm_office__hvac1x__desk
    cm_shelly_dimmer_01
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Roaming
    cm_floorfan1
    cm_floorfan2