#pragma once

/**
 * Interface
 * */

/**
 * AnimatorLight
 * */
#define D_EFFECTS_FUNCTION_SOLID_COLOUR_NAME_CTR  "Solid RGBCCT" // "Solid Colour"
#define D_EFFECTS_FUNCTION_SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_RGBCCT_PALETTE_INDEXED_POSITIONS_01_NAME_CTR "Sun Elevation RGBCCT Solid Palette 01"
#define D_EFFECTS_FUNCTION_SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_RGBCCT_PALETTE_INDEXED_POSITIONS_WITH_AUGMENTED_TRANSITIONS_01_NAME_CTR "Sun Elevation RGBCCT Solid Palette Augmented 01"
#define D_EFFECTS_FUNCTION_SUNPOSITIONS_ELEVATION_ONLY_CONTROLLED_CCT_TEMPERATURE_01_NAME_CTR "Sun Elevation CCT Temp 01"















