// #ifndef MWLEDEFFECTS_prog2_H
// #define MWLEDEFFECTS_prog2_H 0.1

// #include "1_TaskerManager/mTaskerManager.h"

// #ifdef USE_MODULE_LIGHTS_WLED_EFFECTS


//     // builtin modes
//     uint16_t
//       mode_static(void),
//       mode_blink(void),
//       mode_blink_rainbow(void),
//       mode_strobe(void),
//       mode_strobe_rainbow(void),
//       mode_color_wipe(void),
//       mode_color_sweep(void),
//       mode_color_wipe_random(void),
//       mode_color_sweep_random(void),
//       mode_random_color(void),
//       mode_dynamic(void),
//       mode_breath(void),
//       mode_fade(void),
//       mode_scan(void),
//       mode_dual_scan(void),
//       mode_theater_chase(void),
//       mode_theater_chase_rainbow(void),
//       mode_rainbow(void),
//       mode_rainbow_cycle(void),
//       mode_running_lights(void),
//       mode_saw(void),
//       mode_twinkle(void),
//       mode_dissolve(void),
//       mode_dissolve_random(void),
//       mode_sparkle(void),
//       mode_flash_sparkle(void),
//       mode_hyper_sparkle(void),
//       mode_multi_strobe(void),
//       mode_android(void),
//       mode_chase_color(void),
//       mode_chase_random(void),
//       mode_chase_rainbow(void),
//       mode_chase_flash(void),
//       mode_chase_flash_random(void),
//       mode_chase_rainbow_white(void),
//       mode_colorful(void),
//       mode_traffic_light(void),
//       mode_running_color(void),
//       mode_running_red_blue(void),
//       mode_running_random(void),
//       mode_larson_scanner(void),
//       mode_comet(void),
//       mode_fireworks(void),
//       mode_rain(void),
//       mode_merry_christmas(void),
//       mode_halloween(void),
//       mode_fire_flicker(void),
//       mode_gradient(void),
//       mode_loading(void),
//       mode_police(void),
//       mode_police_all(void),
//       mode_two_dots(void),
//       mode_two_areas(void),
//       mode_circus_combustus(void),
//       mode_bicolor_chase(void),
//       mode_tricolor_chase(void),
//       mode_tricolor_wipe(void),
//       mode_tricolor_fade(void),
//       mode_lightning(void),
//       mode_icu(void),
//       mode_multi_comet(void),
//       mode_dual_larson_scanner(void),
//       mode_random_chase(void),
//       mode_oscillate(void),
//       mode_fire_2012(void),
//       mode_pride_2015(void),
//       mode_bpm(void),
//       mode_juggle(void),
//       mode_palette(void),
//       mode_colorwaves(void),
//       mode_fillnoise8(void),
//       mode_noise16_1(void),
//       mode_noise16_2(void),
//       mode_noise16_3(void),
//       mode_noise16_4(void),
//       mode_colortwinkle(void),
//       mode_lake(void),
//       mode_meteor(void),
//       mode_meteor_smooth(void),
//       mode_railway(void),
//       mode_ripple(void),
//       mode_twinklefox(void),
//       mode_twinklecat(void),
//       mode_halloween_eyes(void),
//       mode_static_pattern(void),
//       mode_tri_static_pattern(void),
//       mode_spots(void),
//       mode_spots_fade(void),
//       mode_glitter(void),
//       mode_candle(void),
//       mode_starburst(void),
//       mode_exploding_fireworks(void),
//       mode_bouncing_balls(void),
//       mode_sinelon(void),
//       mode_sinelon_dual(void),
//       mode_sinelon_rainbow(void),
//       mode_popcorn(void),
//       mode_drip(void),
//       mode_plasma(void),
//       mode_percent(void),
//       mode_ripple_rainbow(void),
//       mode_heartbeat(void),
//       mode_pacifica(void),
//       mode_candle_multi(void),
//       mode_solid_glitter(void),
//       mode_sunrise(void),
//       mode_phased(void),
//       mode_twinkleup(void),
//       mode_noisepal(void),
//       mode_sinewave(void),
//       mode_phased_noise(void),
//       mode_flow(void),
//       mode_chunchun(void);

// #endif

// #endif

