#ifndef MWLEDEFFECTS_prog_H
#define MWLEDEFFECTS_prog_H 0.1

#include "1_TaskerManager/mTaskerManager.h"

#ifdef USE_MODULE_LIGHTS_WLED_EFFECTS

#define D_FX_MODE_STATIC_CTR                  "Static"
#define D_FX_MODE_STATIC_PATTERN_CTR          "Solid Pattern"
#define D_FX_MODE_TRI_STATIC_PATTERN_CTR      "Solid Pattern Tri"
#define D_FX_MODE_BLINK_CTR                   "Blink"
#define D_FX_MODE_BREATH_CTR                  "Breathe"
#define D_FX_MODE_COLOR_WIPE_CTR              "Wipe"
#define D_FX_MODE_COLOR_WIPE_RANDOM_CTR       "Wipe Random"
#define D_FX_MODE_RANDOM_COLOR_CTR            "Random Colors"
#define D_FX_MODE_COLOR_SWEEP_CTR             "Sweep"
#define D_FX_MODE_DYNAMIC_CTR                 "Dynamic"
#define D_FX_MODE_RAINBOW_CTR                 "Colorloop"
#define D_FX_MODE_RAINBOW_CYCLE_CTR           "Rainbow"
#define D_FX_MODE_SCAN_CTR                    "Scan"
#define D_FX_MODE_DUAL_SCAN_CTR               "Scan Dual"
#define D_FX_MODE_FADE_CTR                    "Fade"
#define D_FX_MODE_THEATER_CHASE_CTR           "Theater"
#define D_FX_MODE_THEATER_CHASE_RAINBOW_CTR   "Theater Rainbow"
#define D_FX_MODE_RUNNING_LIGHTS_CTR          "Running"
#define D_FX_MODE_SAW_CTR                     "Saw"
#define D_FX_MODE_TWINKLE_CTR                 "Twinkle"
#define D_FX_MODE_DISSOLVE_CTR                "Dissolve"
#define D_FX_MODE_DISSOLVE_RANDOM_CTR         "Dissolve Rnd"
#define D_FX_MODE_SPARKLE_CTR                 "Sparkle"
#define D_FX_MODE_FLASH_SPARKLE_CTR           "Sparkle Dark"
#define D_FX_MODE_HYPER_SPARKLE_CTR           "Sparkle+"
#define D_FX_MODE_STROBE_CTR                  "Strobe"
#define D_FX_MODE_STROBE_RAINBOW_CTR          "Strobe Rainbow"
#define D_FX_MODE_MULTI_STROBE_CTR            "Strobe Mega"
#define D_FX_MODE_BLINK_RAINBOW_CTR           "Blink Rainbow"
#define D_FX_MODE_ANDROID_CTR                 "Android"
#define D_FX_MODE_CHASE_COLOR_CTR             "Chase"
#define D_FX_MODE_CHASE_RANDOM_CTR            "Chase Random"
#define D_FX_MODE_CHASE_RAINBOW_CTR           "Chase Rainbow"
#define D_FX_MODE_CHASE_FLASH_CTR             "Chase Flash"
#define D_FX_MODE_CHASE_FLASH_RANDOM_CTR      "Chase Flash Rnd"
#define D_FX_MODE_CHASE_RAINBOW_WHITE_CTR     "Rainbow Runner"
#define D_FX_MODE_COLORFUL_CTR                "Colorful"
#define D_FX_MODE_TRAFFIC_LIGHT_CTR           "Traffic Light"
#define D_FX_MODE_COLOR_SWEEP_RANDOM_CTR      "Sweep Random"
#define D_FX_MODE_RUNNING_COLOR_CTR           "Running 2"
#define D_FX_MODE_RUNNING_RED_BLUE_CTR        "Red & Blue"
#define D_FX_MODE_RUNNING_RANDOM_CTR          "Stream"
#define D_FX_MODE_LARSON_SCANNER_CTR          "Scanner"
#define D_FX_MODE_COMET_CTR                   "Lighthouse"
#define D_FX_MODE_FIREWORKS_CTR               "Fireworks"
#define D_FX_MODE_RAIN_CTR                    "Rain"
#define D_FX_MODE_MERRY_CHRISTMAS_CTR         "Merry Christmas"
#define D_FX_MODE_FIRE_FLICKER_CTR            "Fire Flicker"
#define D_FX_MODE_GRADIENT_CTR                "Gradient"
#define D_FX_MODE_LOADING_CTR                 "Loading"
#define D_FX_MODE_POLICE_CTR                  "Police"
#define D_FX_MODE_POLICE_ALL_CTR              "Police All"
#define D_FX_MODE_TWO_DOTS_CTR                "Two Dots"
#define D_FX_MODE_TWO_AREAS_CTR               "Two Areas"
#define D_FX_MODE_CIRCUS_COMBUSTUS_CTR        "Circus"
#define D_FX_MODE_HALLOWEEN_CTR               "Halloween"
#define D_FX_MODE_TRICOLOR_CHASE_CTR          "Tri Chase"
#define D_FX_MODE_TRICOLOR_WIPE_CTR           "Tri Wipe"
#define D_FX_MODE_TRICOLOR_FADE_CTR           "Tri Fade"
#define D_FX_MODE_LIGHTNING_CTR               "Lightning"
#define D_FX_MODE_ICU_CTR                     "ICU"
#define D_FX_MODE_MULTI_COMET_CTR             "Multi Comet"
#define D_FX_MODE_DUAL_LARSON_SCANNER_CTR     "Scanner Dual"
#define D_FX_MODE_RANDOM_CHASE_CTR            "Stream 2"
#define D_FX_MODE_OSCILLATE_CTR               "Oscillate"
#define D_FX_MODE_PRIDE_2015_CTR              "Pride 2015"
#define D_FX_MODE_JUGGLE_CTR                  "Juggle"
#define D_FX_MODE_PALETTE_CTR                 "Palette"
#define D_FX_MODE_FIRE_2012_CTR               "Fire 2012"
#define D_FX_MODE_COLORWAVES_CTR              "Colorwaves"
#define D_FX_MODE_BPM_CTR                     "Bpm"
#define D_FX_MODE_FILLNOISE8_CTR              "Fill Noise"
#define D_FX_MODE_NOISE16_1_CTR               "Noise 1"
#define D_FX_MODE_NOISE16_2_CTR               "Noise 2"
#define D_FX_MODE_NOISE16_3_CTR               "Noise 3"
#define D_FX_MODE_NOISE16_4_CTR               "Noise 4"
#define D_FX_MODE_COLORTWINKLE_CTR            "Colortwinkles"
#define D_FX_MODE_LAKE_CTR                    "Lake"
#define D_FX_MODE_METEOR_CTR                  "Meteor"
#define D_FX_MODE_METEOR_SMOOTH_CTR           "Meteor Smooth"
#define D_FX_MODE_RAILWAY_CTR                 "Railway"
#define D_FX_MODE_RIPPLE_CTR                  "Ripple"
#define D_FX_MODE_TWINKLEFOX_CTR              "Twinklefox"
#define D_FX_MODE_TWINKLECAT_CTR              "Twinklecat"
#define D_FX_MODE_HALLOWEEN_EYES_CTR          "Halloween Eyes"
#define D_FX_MODE_SPOTS_CTR                   "Spots"
#define D_FX_MODE_SPOTS_FADE_CTR              "Spots Fade"
#define D_FX_MODE_GLITTER_CTR                 "Glitter"
#define D_FX_MODE_CANDLE_CTR                  "Candle"
#define D_FX_MODE_STARBURST_CTR               "Fireworks Starburst"
#define D_FX_MODE_EXPLODING_FIREWORKS_CTR     "Fireworks 1D"
#define D_FX_MODE_BOUNCINGBALLS_CTR           "Bouncing Balls"
#define D_FX_MODE_SINELON_CTR                 "Sinelon"
#define D_FX_MODE_SINELON_DUAL_CTR            "Sinelon Dual"
#define D_FX_MODE_SINELON_RAINBOW_CTR         "Sinelon Rainbow"
#define D_FX_MODE_POPCORN_CTR                 "Popcorn"
#define D_FX_MODE_DRIP_CTR                    "Drip"
#define D_FX_MODE_PLASMA_CTR                  "Plasma"
#define D_FX_MODE_PERCENT_CTR                 "Percent"
#define D_FX_MODE_RIPPLE_RAINBOW_CTR          "Ripple Rainbow"
#define D_FX_MODE_HEARTBEAT_CTR               "Heartbeat"
#define D_FX_MODE_PACIFICA_CTR                "Pacifica"
#define D_FX_MODE_CANDLE_MULTI_CTR            "Candle Multi"
#define D_FX_MODE_SOLID_GLITTER_CTR           "Solid Glitter"
#define D_FX_MODE_SUNRISE_CTR                 "Sunrise"
#define D_FX_MODE_PHASED_CTR                  "Phased"
#define D_FX_MODE_TWINKLEUP_CTR               "Twinkleup"
#define D_FX_MODE_NOISEPAL_CTR                "Noise Pal"
#define D_FX_MODE_SINEWAVE_CTR                "Sine"
#define D_FX_MODE_PHASEDNOISE_CTR             "Phased Noise"
#define D_FX_MODE_FLOW_CTR                    "Flow"
#define D_FX_MODE_CHUNCHUN_CTR                "Chunchun"


// Doing this with memcmp_p until effects are fully designed, then for memory reasons
// move to "dlist", "SearchForTextIndexedID" and "GetTextIndexed_P"
DEFINE_PGM_CTR(PM_FX_MODE_STATIC_CTR)                 D_FX_MODE_STATIC_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_BLINK_CTR)                  D_FX_MODE_BLINK_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_BREATH_CTR)                 D_FX_MODE_BREATH_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLOR_WIPE_CTR)             D_FX_MODE_COLOR_WIPE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLOR_WIPE_RANDOM_CTR)      D_FX_MODE_COLOR_WIPE_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RANDOM_COLOR_CTR)           D_FX_MODE_RANDOM_COLOR_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLOR_SWEEP_CTR)            D_FX_MODE_COLOR_SWEEP_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DYNAMIC_CTR)                D_FX_MODE_DYNAMIC_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RAINBOW_CTR)                D_FX_MODE_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RAINBOW_CYCLE_CTR)          D_FX_MODE_RAINBOW_CYCLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SCAN_CTR)                   D_FX_MODE_SCAN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DUAL_SCAN_CTR)              D_FX_MODE_DUAL_SCAN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FADE_CTR)                   D_FX_MODE_FADE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_THEATER_CHASE_CTR)          D_FX_MODE_THEATER_CHASE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_THEATER_CHASE_RAINBOW_CTR)  D_FX_MODE_THEATER_CHASE_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RUNNING_LIGHTS_CTR)         D_FX_MODE_RUNNING_LIGHTS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SAW_CTR)                    D_FX_MODE_SAW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWINKLE_CTR)                D_FX_MODE_TWINKLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DISSOLVE_CTR)               D_FX_MODE_DISSOLVE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DISSOLVE_RANDOM_CTR)        D_FX_MODE_DISSOLVE_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SPARKLE_CTR)                D_FX_MODE_SPARKLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FLASH_SPARKLE_CTR)          D_FX_MODE_FLASH_SPARKLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_HYPER_SPARKLE_CTR)          D_FX_MODE_HYPER_SPARKLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_STROBE_CTR)                 D_FX_MODE_STROBE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_STROBE_RAINBOW_CTR)         D_FX_MODE_STROBE_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_MULTI_STROBE_CTR)           D_FX_MODE_MULTI_STROBE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_BLINK_RAINBOW_CTR)          D_FX_MODE_BLINK_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_ANDROID_CTR)                D_FX_MODE_ANDROID_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_COLOR_CTR)            D_FX_MODE_CHASE_COLOR_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_RANDOM_CTR)           D_FX_MODE_CHASE_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_RAINBOW_CTR)          D_FX_MODE_CHASE_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_FLASH_CTR)            D_FX_MODE_CHASE_FLASH_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_FLASH_RANDOM_CTR)     D_FX_MODE_CHASE_FLASH_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHASE_RAINBOW_WHITE_CTR)    D_FX_MODE_CHASE_RAINBOW_WHITE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLORFUL_CTR)               D_FX_MODE_COLORFUL_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TRAFFIC_LIGHT_CTR)          D_FX_MODE_TRAFFIC_LIGHT_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLOR_SWEEP_RANDOM_CTR)     D_FX_MODE_COLOR_SWEEP_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RUNNING_COLOR_CTR)          D_FX_MODE_RUNNING_COLOR_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RUNNING_RED_BLUE_CTR)       D_FX_MODE_RUNNING_RED_BLUE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RUNNING_RANDOM_CTR)         D_FX_MODE_RUNNING_RANDOM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_LARSON_SCANNER_CTR)         D_FX_MODE_LARSON_SCANNER_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COMET_CTR)                  D_FX_MODE_COMET_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FIREWORKS_CTR)              D_FX_MODE_FIREWORKS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RAIN_CTR)                   D_FX_MODE_RAIN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_MERRY_CHRISTMAS_CTR)        D_FX_MODE_MERRY_CHRISTMAS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FIRE_FLICKER_CTR)           D_FX_MODE_FIRE_FLICKER_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_GRADIENT_CTR)               D_FX_MODE_GRADIENT_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_LOADING_CTR)                D_FX_MODE_LOADING_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_POLICE_CTR)                 D_FX_MODE_POLICE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_POLICE_ALL_CTR)             D_FX_MODE_POLICE_ALL_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWO_DOTS_CTR)               D_FX_MODE_TWO_DOTS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWO_AREAS_CTR)              D_FX_MODE_TWO_AREAS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CIRCUS_COMBUSTUS_CTR)       D_FX_MODE_CIRCUS_COMBUSTUS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_HALLOWEEN_CTR)              D_FX_MODE_HALLOWEEN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TRICOLOR_CHASE_CTR)         D_FX_MODE_TRICOLOR_CHASE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TRICOLOR_WIPE_CTR)          D_FX_MODE_TRICOLOR_WIPE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TRICOLOR_FADE_CTR)          D_FX_MODE_TRICOLOR_FADE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_LIGHTNING_CTR)              D_FX_MODE_LIGHTNING_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_ICU_CTR)                    D_FX_MODE_ICU_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_MULTI_COMET_CTR)            D_FX_MODE_MULTI_COMET_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DUAL_LARSON_SCANNER_CTR)    D_FX_MODE_DUAL_LARSON_SCANNER_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RANDOM_CHASE_CTR)           D_FX_MODE_RANDOM_CHASE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_OSCILLATE_CTR)              D_FX_MODE_OSCILLATE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PRIDE_2015_CTR)             D_FX_MODE_PRIDE_2015_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_JUGGLE_CTR)                 D_FX_MODE_JUGGLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PALETTE_CTR)                D_FX_MODE_PALETTE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FIRE_2012_CTR)              D_FX_MODE_FIRE_2012_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLORWAVES_CTR)             D_FX_MODE_COLORWAVES_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_BPM_CTR)                    D_FX_MODE_BPM_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FILLNOISE8_CTR)             D_FX_MODE_FILLNOISE8_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_NOISE16_1_CTR)              D_FX_MODE_NOISE16_1_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_NOISE16_2_CTR)              D_FX_MODE_NOISE16_2_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_NOISE16_3_CTR)              D_FX_MODE_NOISE16_3_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_NOISE16_4_CTR)              D_FX_MODE_NOISE16_4_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_COLORTWINKLE_CTR)           D_FX_MODE_COLORTWINKLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_LAKE_CTR)                   D_FX_MODE_LAKE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_METEOR_CTR)                 D_FX_MODE_METEOR_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_METEOR_SMOOTH_CTR)          D_FX_MODE_METEOR_SMOOTH_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RAILWAY_CTR)                D_FX_MODE_RAILWAY_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RIPPLE_CTR)                 D_FX_MODE_RIPPLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWINKLEFOX_CTR)             D_FX_MODE_TWINKLEFOX_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWINKLECAT_CTR)             D_FX_MODE_TWINKLECAT_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_HALLOWEEN_EYES_CTR)         D_FX_MODE_HALLOWEEN_EYES_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_STATIC_PATTERN_CTR)         D_FX_MODE_STATIC_PATTERN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TRI_STATIC_PATTERN_CTR)     D_FX_MODE_TRI_STATIC_PATTERN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SPOTS_CTR)                  D_FX_MODE_SPOTS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SPOTS_FADE_CTR)             D_FX_MODE_SPOTS_FADE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_GLITTER_CTR)                D_FX_MODE_GLITTER_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CANDLE_CTR)                 D_FX_MODE_CANDLE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_STARBURST_CTR)              D_FX_MODE_STARBURST_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_EXPLODING_FIREWORKS_CTR)    D_FX_MODE_EXPLODING_FIREWORKS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_BOUNCINGBALLS_CTR)          D_FX_MODE_BOUNCINGBALLS_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SINELON_CTR)                D_FX_MODE_SINELON_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SINELON_DUAL_CTR)           D_FX_MODE_SINELON_DUAL_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SINELON_RAINBOW_CTR)        D_FX_MODE_SINELON_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_POPCORN_CTR)                D_FX_MODE_POPCORN_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_DRIP_CTR)                   D_FX_MODE_DRIP_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PLASMA_CTR)                 D_FX_MODE_PLASMA_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PERCENT_CTR)                D_FX_MODE_PERCENT_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_RIPPLE_RAINBOW_CTR)         D_FX_MODE_RIPPLE_RAINBOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_HEARTBEAT_CTR)              D_FX_MODE_HEARTBEAT_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PACIFICA_CTR)               D_FX_MODE_PACIFICA_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CANDLE_MULTI_CTR)           D_FX_MODE_CANDLE_MULTI_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SOLID_GLITTER_CTR)          D_FX_MODE_SOLID_GLITTER_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SUNRISE_CTR)                D_FX_MODE_SUNRISE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PHASED_CTR)                 D_FX_MODE_PHASED_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_TWINKLEUP_CTR)              D_FX_MODE_TWINKLEUP_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_NOISEPAL_CTR)               D_FX_MODE_NOISEPAL_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_SINEWAVE_CTR)               D_FX_MODE_SINEWAVE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_PHASEDNOISE_CTR)            D_FX_MODE_PHASEDNOISE_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_FLOW_CTR)                   D_FX_MODE_FLOW_CTR;
DEFINE_PGM_CTR(PM_FX_MODE_CHUNCHUN_CTR)               D_FX_MODE_CHUNCHUN_CTR;


DEFINE_PGM_CTR(PM_FX_MODES_NAMES_CTR)
{
  // Static
  D_FX_MODE_STATIC_CTR  "|"
  D_FX_MODE_STATIC_PATTERN_CTR  "|"
  D_FX_MODE_TRI_STATIC_PATTERN_CTR  "|"
  D_FX_MODE_SPOTS_CTR  "|"
  D_FX_MODE_PERCENT_CTR  "|"
    // One colour changes
  D_FX_MODE_RANDOM_COLOR_CTR  "|"
    // Wipe
  D_FX_MODE_COLOR_WIPE_CTR  "|" 
  D_FX_MODE_COLOR_WIPE_RANDOM_CTR  "|"
  D_FX_MODE_COLOR_SWEEP_CTR  "|"
  D_FX_MODE_COLOR_SWEEP_RANDOM_CTR  "|"
  D_FX_MODE_TRICOLOR_WIPE_CTR  "|"
  D_FX_MODE_ANDROID_CTR  "|"
  D_FX_MODE_RUNNING_RED_BLUE_CTR  "|"
  D_FX_MODE_RUNNING_COLOR_CTR  "|"
  D_FX_MODE_RUNNING_RANDOM_CTR  "|"
  D_FX_MODE_GRADIENT_CTR  "|"
  D_FX_MODE_LOADING_CTR  "|"
  D_FX_MODE_POLICE_CTR  "|"
  D_FX_MODE_POLICE_ALL_CTR  "|"
  D_FX_MODE_TWO_DOTS_CTR  "|"
  D_FX_MODE_TWO_AREAS_CTR  "|"
  D_FX_MODE_MULTI_COMET_CTR  "|"
  D_FX_MODE_OSCILLATE_CTR  "|"
  D_FX_MODE_BPM_CTR  "|"
  D_FX_MODE_JUGGLE_CTR  "|"
  D_FX_MODE_PALETTE_CTR  "|"
  D_FX_MODE_COLORWAVES_CTR  "|"
  D_FX_MODE_LAKE_CTR  "|"
  D_FX_MODE_GLITTER_CTR  "|"
  D_FX_MODE_METEOR_CTR  "|"
  D_FX_MODE_METEOR_SMOOTH_CTR  "|"
  D_FX_MODE_PRIDE_2015_CTR  "|"
  D_FX_MODE_RIPPLE_RAINBOW_CTR  "|"
  D_FX_MODE_PACIFICA_CTR  "|"
  D_FX_MODE_SUNRISE_CTR  "|"
  D_FX_MODE_SINEWAVE_CTR  "|"
  D_FX_MODE_FLOW_CTR  "|"
  D_FX_MODE_PHASEDNOISE_CTR  "|"
  D_FX_MODE_PHASED_CTR  "|"
  D_FX_MODE_RUNNING_LIGHTS_CTR  "|"
  D_FX_MODE_RAINBOW_CYCLE_CTR  "|"
  D_FX_MODE_MERRY_CHRISTMAS_CTR  "|"
  D_FX_MODE_HALLOWEEN_CTR  "|"
    // Chase
  D_FX_MODE_CHASE_COLOR_CTR  "|"
  D_FX_MODE_CHASE_RANDOM_CTR  "|"
  D_FX_MODE_CHASE_RAINBOW_CTR  "|" 
  D_FX_MODE_CHASE_FLASH_CTR  "|"
  D_FX_MODE_CHASE_FLASH_RANDOM_CTR  "|" 
  D_FX_MODE_CHASE_RAINBOW_WHITE_CTR  "|"
  D_FX_MODE_THEATER_CHASE_CTR  "|"
  D_FX_MODE_THEATER_CHASE_RAINBOW_CTR  "|"
  D_FX_MODE_TRICOLOR_CHASE_CTR  "|"
  D_FX_MODE_RANDOM_CHASE_CTR  "|"
  D_FX_MODE_CIRCUS_COMBUSTUS_CTR  "|"
    // Breathe/Fade/Pulse
  D_FX_MODE_BREATH_CTR  "|"
  D_FX_MODE_FADE_CTR  "|"
  D_FX_MODE_TRICOLOR_FADE_CTR  "|"
  D_FX_MODE_SPOTS_FADE_CTR  "|"
    // Fireworks
  D_FX_MODE_FIREWORKS_CTR  "|"
  D_FX_MODE_STARBURST_CTR  "|"
  D_FX_MODE_EXPLODING_FIREWORKS_CTR  "|"
  D_FX_MODE_RAIN_CTR  "|"
    // Sparkle/Twinkle
  D_FX_MODE_SOLID_GLITTER_CTR  "|"
  D_FX_MODE_POPCORN_CTR  "|"
  D_FX_MODE_PLASMA_CTR  "|"
  D_FX_MODE_FIRE_FLICKER_CTR  "|"
  D_FX_MODE_SPARKLE_CTR  "|"
  D_FX_MODE_FLASH_SPARKLE_CTR  "|"
  D_FX_MODE_HYPER_SPARKLE_CTR  "|"
  D_FX_MODE_TWINKLE_CTR  "|"
  D_FX_MODE_COLORTWINKLE_CTR  "|"
  D_FX_MODE_TWINKLEFOX_CTR  "|"
  D_FX_MODE_TWINKLECAT_CTR  "|"
  D_FX_MODE_TWINKLEUP_CTR  "|"
  D_FX_MODE_DYNAMIC_CTR  "|"
  D_FX_MODE_SAW_CTR  "|"
  D_FX_MODE_DISSOLVE_CTR  "|"
  D_FX_MODE_DISSOLVE_RANDOM_CTR  "|"
  D_FX_MODE_COLORFUL_CTR  "|"
  D_FX_MODE_TRAFFIC_LIGHT_CTR  "|"
  D_FX_MODE_CANDLE_CTR  "|"
  D_FX_MODE_CANDLE_MULTI_CTR  "|"
  D_FX_MODE_HALLOWEEN_EYES_CTR  "|"
  #ifdef ENABLE_ADVANCED_EFFECTS  
    // Blink/Strobe
  D_FX_MODE_BLINK_CTR  "|"
  D_FX_MODE_BLINK_RAINBOW_CTR  "|"
  D_FX_MODE_STROBE_CTR  "|"
  D_FX_MODE_MULTI_STROBE_CTR  "|"
  D_FX_MODE_STROBE_RAINBOW_CTR  "|" 
  D_FX_MODE_RAINBOW_CTR  "|"
  D_FX_MODE_LIGHTNING_CTR  "|"     
  D_FX_MODE_FIRE_2012_CTR  "|"
  D_FX_MODE_RAILWAY_CTR  "|"
  D_FX_MODE_HEARTBEAT_CTR  "|" 
    // Noise
  D_FX_MODE_FILLNOISE8_CTR  "|"
  D_FX_MODE_NOISE16_1_CTR  "|"
  D_FX_MODE_NOISE16_2_CTR  "|"
  D_FX_MODE_NOISE16_3_CTR  "|"
  D_FX_MODE_NOISE16_4_CTR  "|"
  D_FX_MODE_NOISEPAL_CTR  "|"
    // Scan
  D_FX_MODE_SCAN_CTR  "|"
  D_FX_MODE_DUAL_SCAN_CTR  "|"
  D_FX_MODE_LARSON_SCANNER_CTR  "|"
  D_FX_MODE_DUAL_LARSON_SCANNER_CTR  "|"
  D_FX_MODE_ICU_CTR  "|"
  D_FX_MODE_RIPPLE_CTR  "|"
  D_FX_MODE_COMET_CTR  "|"
  D_FX_MODE_CHUNCHUN_CTR  "|"
  D_FX_MODE_BOUNCINGBALLS_CTR  "|"
  D_FX_MODE_SINELON_CTR  "|"
  D_FX_MODE_SINELON_DUAL_CTR  "|"
  D_FX_MODE_SINELON_RAINBOW_CTR  "|"
  D_FX_MODE_DRIP_CTR
  #endif // ENABLE_ADVANCED_EFFECTS   
};



#endif

#endif

