/*
* Binary array for the Web UI.
* gzip is used for smaller size and improved speeds.
* Header with extern definition to reduce file size with multiple inclusions of array in multiple files
*/

#include "stdint.h"

// Autogenerated from HomeControlSystem/data/root_page.htm, do not edit!!
const uint16_t PAGE_ROOT_L = 17298;
extern const uint8_t PAGE_ROOT[]
;
