/*
* Binary array for the Web UI.
* gzip is used for smaller size and improved speeds.
* Header with extern definition to reduce file size with multiple inclusions of array in multiple files
*/


#ifndef DEFINE_HEADER_PAGE_ROOT2
#define DEFINE_HEADER_PAGE_ROOT2

#include "stdint.h"

// Autogenerated from HomeControlSystem/data/root_page.htm, do not edit!!
const uint16_t PAGE_ROOT_L = 17320;
extern const uint8_t PAGE_ROOT[];
#endif
