#pragma once

void SubTask_Flasher_Animate_Function_SunPositions_Solid_Colour_Based_On_Sun_Elevation_01();
void AnimationProcess_SunPositions_Solid_Colour_Based_On_Sun_Elevation_01(const AnimationParam& param);